# Mini-Projeto — Análise Exploratória de Dados de Varejo

**Autor:** Otávio Diniz  
**Curso:** SC TEC — Análise de Dados com Python  
**Turma:** T8  
**Módulo:** 1 — Semana 7

## Objetivo

Investigar a estrutura e a qualidade de uma base de dados de varejo, aplicar procedimentos justificados de tratamento e interpretar os resultados.

## Fonte dos dados

**Dataset:** Base Varejo  
**Fonte:** [Kaggle — Base Varejo](https://www.kaggle.com/datasets/namespaiva/base-varejo/data)  
**Responsável pela publicação:** João Pedro Paiva Cardoso  
**Versão:** 1 — 03/04/2023  
**Arquivo:** `Base Varejo.csv`

## Organização do projeto

O desenvolvimento técnico percorre as Sprints 1 a 5, da leitura e do diagnóstico à limpeza, às funções, às análises, à exportação e à documentação. A Sprint 0 corresponde à preparação auxiliar do ambiente e dos dados; a Sprint 6 é destinada à revisão e à entrega, conforme o enunciado institucional.

Cada etapa apresentará o objetivo, o código utilizado, os resultados encontrados e sua interpretação.

---

# Preparação inicial — Sprint 0 (etapa auxiliar)

## CP0.1 — Acesso e verificação do arquivo

### O que faremos?

Antes de começar a análise, precisamos garantir que a base de dados esteja disponível para leitura.

O projeto será desenvolvido no **Google Colab**, ambiente que permite executar códigos Python diretamente pelo navegador.

A base utilizada está no formato **CSV**, um arquivo de texto que organiza informações em linhas e colunas, separadas por um caractere específico.

Neste caso, utilizaremos o arquivo `Base Varejo.csv`, disponibilizado no Kaggle.

### Como o arquivo será carregado?

Para facilitar a reprodução do projeto, o notebook permitirá selecionar o arquivo CSV diretamente do computador, sem depender de uma pasta específica do Google Drive.

Depois do envio, verificaremos se o arquivo está disponível e consultaremos seu nome e tamanho.

### Por que essa etapa é importante?

Um projeto reproduzível deve permitir que outras pessoas executem o mesmo código utilizando a mesma fonte de dados.

Neste checkpoint, nosso objetivo é apenas preparar o arquivo. A leitura e a investigação das informações começam na Sprint 1.

In [2]:
# CP0.1 — Acesso e verificação do arquivo

from google.colab import files
from pathlib import Path

# Selecionar a base de dados
print("Selecione o arquivo Base Varejo.csv")
files.upload()

# Identificar o arquivo enviado
arquivo_base = Path("Base Varejo.csv")

# Conferir sua disponibilidade
print("Arquivo encontrado:", arquivo_base.is_file())

if arquivo_base.is_file():
    print("Nome do arquivo:", arquivo_base.name)
    print("Tamanho em bytes:", arquivo_base.stat().st_size)

Selecione o arquivo Base Varejo.csv

Saving Base Varejo.csv to Base Varejo.csv
Arquivo encontrado: True
Nome do arquivo: Base Varejo.csv
Tamanho em bytes: 48773819

# Sprint 1 — Leitura e diagnóstico

## CP1.1 — Importação e estrutura da base

**Pergunta:** quais dados foram recebidos e como estão organizados?

Nesta etapa, utilizaremos a biblioteca Pandas para carregar o arquivo CSV e conhecer sua estrutura inicial.

Vamos observar:
- As primeiras cinco linhas da tabela.
- A quantidade de registros e colunas.
- Os nomes dos campos.
- Os tipos de dados identificados pelo Pandas.
- O que cada linha pode representar na base de varejo.

**Dica de Ouro:** a leitura da estrutura não é uma limpeza. Antes de modificar os dados, precisamos compreender o significado dos registros e identificar possíveis problemas.

In [3]:
# CP1.1 — Leitura da base e inspeção da estrutura

import pandas as pd

# Ler a base de dados
df_bruto = pd.read_csv(
    arquivo_base,
    sep=";"
)

# Mostrar as primeiras linhas
print("Primeiras cinco linhas:")
display(df_bruto.head())

# Conferir a estrutura
print("Quantidade de linhas:", df_bruto.shape[0])
print("Quantidade de colunas:", df_bruto.shape[1])

print("Nomes das colunas:")
print(df_bruto.columns.tolist())

# Conferir os tipos e valores preenchidos
print("Informações gerais:")
df_bruto.info()

Primeiras cinco linhas:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

Quantidade de linhas: 830000
Quantidade de colunas: 14
Nomes das colunas:
['DATA', 'CO_ID', 'CL_ID', 'CL_GENERO', 'CL_EC', 'CL_FHL', 'CL_SEG', 'PR_ID', 'PR_CAT', 'PR_NOME', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']
Informações gerais:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  object
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  object
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  object
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  object
 9   PR_NOME      830000 non-null  object
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), object(5)
memory usage: 88.7+ MB

In [4]:
# CP1.1 — Visualização das colunas selecionadas
# Selecionar algumas colunas para facilitar a leitura
colunas_selecionadas = [
    "DATA",
    "CO_ID",
    "CL_ID",
    "PR_ID",
    "PR_CAT",
    "PR_NOME"
]

display(df_bruto[colunas_selecionadas].head())

         DATA  CO_ID  CL_ID  PR_ID     PR_CAT               PR_NOME
0  01/02/2019   1000    534     67    BEBIDAS  REFRIGERANTE GUARANA
1  01/02/2019   1000    534     70    BEBIDAS   REFRIGERANTE OUTROS
2  01/02/2019   1000    534    178    HIGIENE       LENCO UMEDECIDO
3  01/02/2019   1000    534      4  ALIMENTOS               ABACAXI
4  01/02/2019   1000    534    175    LIMPEZA     LIMPADOR MULTIUSO

### Interpretação dos resultados do CP1.1

A leitura da base foi realizada com a biblioteca Pandas, utilizando `read_csv()` e o separador `;`.

O arquivo contém 830.000 registros e 14 colunas físicas. Dessas colunas, dez possuem nomes definidos e quatro aparecem sem identificação.

A visualização das primeiras linhas permite começar a investigar a relação entre datas, compras, clientes e produtos.

A presença de identificadores repetidos não significa necessariamente erro: precisamos compreender o que cada linha representa antes de decidir sobre possíveis duplicatas.

**Próxima etapa:** realizar o diagnóstico da qualidade dos dados, verificando valores ausentes, campos em branco, duplicatas e inconsistências textuais.

## CP1.2 — Diagnóstico da qualidade dos dados

### O que vamos investigar?

No checkpoint anterior, conhecemos a estrutura da Base Varejo. Agora precisamos verificar a qualidade das informações recebidas.

Uma base pode conter problemas que não aparecem quando observamos apenas as primeiras cinco linhas. Por isso, vamos investigar todo o conjunto de dados antes de realizar qualquer alteração.

**Pergunta principal:** existem informações ausentes, registros repetidos ou diferenças na escrita dos textos que possam comprometer nossa análise?

### O que será verificado?

**1. Valores ausentes**

Usaremos `isna()` para identificar campos sem informação. Em Pandas, esses valores podem aparecer como `NaN`.

**2. Textos vazios e espaços**

Um campo pode conter somente espaços ou ter espaços desnecessários antes ou depois do texto. Vamos verificar essas situações utilizando `str.strip()`.

**3. Duplicatas**

Usaremos `duplicated()` para identificar linhas completamente repetidas.

É importante lembrar que um cliente pode realizar várias compras e que uma compra pode conter vários produtos. Por isso, uma repetição não deve ser removida sem investigar seu significado.

**4. Inconsistências textuais**

Vamos observar as categorias e os textos existentes para identificar diferenças de escrita ou marcadores como `#N/D`.

### Conhecimentos utilizados

Neste checkpoint, aplicaremos recursos estudados anteriormente:

- Variáveis, listas e laços `for` do Python.
- Condicionais e leitura de resultados.
- DataFrames e seleção de colunas.
- Métodos `isna()`, `sum()`, `duplicated()`, `unique()` e operações com textos do Pandas.

**Dica de Ouro:** identificar um problema não significa que devemos corrigi-lo imediatamente. Primeiro precisamos conhecer sua quantidade, sua natureza e seu possível impacto. As decisões de limpeza serão realizadas na Sprint 2.

In [5]:
# CP1.2 — Verificação de valores ausentes

print("Valores ausentes por coluna:")

ausentes = df_bruto.isna().sum()

display(ausentes)

Valores ausentes por coluna:

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

In [6]:
# CP1.2 — Verificação dos campos de texto

colunas_texto = [
    "DATA",
    "CL_GENERO",
    "CL_SEG",
    "PR_CAT",
    "PR_NOME"
]

for coluna in colunas_texto:

    texto = df_bruto[coluna].astype("string")

    # Campos vazios ou contendo apenas espaços
    em_branco = texto.str.strip().eq("").sum()

    # Valores com espaços no início ou no fim
    com_espacos = texto.ne(texto.str.strip()).sum()

    print(
        coluna,
        "- Em branco:", em_branco,
        "- Com espaços nas extremidades:", com_espacos
    )

DATA - Em branco: 0 - Com espaços nas extremidades: 0
CL_GENERO - Em branco: 0 - Com espaços nas extremidades: 0
CL_SEG - Em branco: 0 - Com espaços nas extremidades: 0
PR_CAT - Em branco: 0 - Com espaços nas extremidades: 0
PR_NOME - Em branco: 0 - Com espaços nas extremidades: 0

In [7]:
# CP1.2 — Verificação de registros repetidos

print("Linhas completamente duplicadas:")
print(df_bruto.duplicated().sum())

print("\nIdentificadores distintos:")

print(
    "Compras:",
    df_bruto["CO_ID"].nunique()
)

print(
    "Clientes:",
    df_bruto["CL_ID"].nunique()
)

print(
    "Produtos:",
    df_bruto["PR_ID"].nunique()
)

Linhas completamente duplicadas:
96553

Identificadores distintos:
Compras: 18471
Clientes: 1000
Produtos: 229

In [8]:
# CP1.2 — Conferência das categorias textuais

for coluna in ["CL_GENERO", "CL_SEG", "PR_CAT"]:

    print("\nColuna:", coluna)

    print(df_bruto[coluna].unique())


# Conferir marcadores textuais de informação ausente
print("\nOcorrências do marcador #N/D:")

for coluna in ["PR_CAT", "PR_NOME"]:

    quantidade = (
        df_bruto[coluna]
        .astype("string")
        .str.strip()
        .eq("#N/D")
        .sum()
    )

    print(coluna, ":", quantidade)


# Observar alguns nomes de produtos
print("\nExemplos de nomes de produtos:")

display(
    df_bruto["PR_NOME"]
    .value_counts()
    .head(10)
)

Coluna: CL_GENERO
['M' 'F']

Coluna: CL_SEG
['C' 'B' 'A']

Coluna: PR_CAT
['BEBIDAS' 'HIGIENE' 'ALIMENTOS' 'LIMPEZA' 'ACESSORIOS' 'PET' '#N/D']

Ocorrências do marcador #N/D:
PR_CAT : 3650
PR_NOME : 3650

Exemplos de nomes de produtos:

PR_NOME
PRESUNTO COZIDO       14381
SARDINHA               7490
GEL                    7399
BANANA                 7385
DESENGORDURANTE        7378
MODELADOR              7363
BIFE DE COXAO MOLE     7355
REMOVEDOR              7350
ESCOVA DE DENTE        7346
PAPINHA INFANTIL       7346
Name: count, dtype: int64

### Interpretação dos resultados do CP1.2

**1. Valores ausentes**

A verificação com `isna().sum()` foi realizada nas 14 colunas da base.

Foram identificadas quatro colunas completamente vazias:

| Coluna | Valores ausentes |
|---|---:|
| `Unnamed: 10` | 830.000 |
| `Unnamed: 11` | 830.000 |
| `Unnamed: 12` | 830.000 |
| `Unnamed: 13` | 830.000 |

As dez colunas nomeadas não apresentaram valores ausentes reconhecidos pelo Pandas.

**Interpretação:** as quatro colunas sem nome não apresentam informações preenchidas. Sua possível remoção será avaliada durante a limpeza, mantendo o arquivo original preservado.


**2. Textos vazios e espaços**

Das 14 colunas, cinco armazenam informações textuais: `DATA`, `CL_GENERO`, `CL_SEG`, `PR_CAT` e `PR_NOME`.

As outras cinco colunas nomeadas foram identificadas como numéricas, incluindo identificadores e códigos. As quatro colunas restantes são os campos sem nome já identificados como vazios.

A verificação de espaços foi aplicada às cinco colunas textuais, utilizando `str.strip()`.

**Resultado:** não foram encontrados textos vazios, campos compostos apenas por espaços ou espaços nas extremidades dos valores examinados.

**Interpretação:** todas as 14 colunas foram verificadas quanto a valores ausentes; o exame adicional de espaços foi realizado nas cinco colunas textuais. Isso não elimina a possibilidade de outras inconsistências, como códigos desconhecidos ou marcadores textuais de informação indisponível.


**3. Duplicatas e identificadores distintos**

O método `duplicated()` identificou **96.553 linhas completamente repetidas**, além das primeiras ocorrências.

Também foram identificados:

| Identificador | Quantidade distinta |
|---|---:|
| Compras (`CO_ID`) | 18.471 |
| Clientes (`CL_ID`) | 1.000 |
| Produtos (`PR_ID`) | 229 |

**Interpretação:** a repetição de um identificador não significa necessariamente duplicidade indevida.

Um cliente pode realizar várias compras, e uma compra pode conter diversos produtos. Portanto, o mesmo `CL_ID` pode aparecer em muitos registros sem que exista duplicação do seu cadastro.

Da mesma maneira, um produto pode aparecer em compras diferentes ou mais de uma vez na mesma compra.

A duplicação indevida de um cadastro de cliente seria um problema diferente, que precisaria de informações cadastrais adicionais para ser comprovado.

As 96.553 linhas completamente repetidas merecem investigação. A base não apresenta quantidade vendida nem identificador individual de cada item, o que impede distinguir com segurança uma repetição legítima de um possível erro de registro.

**Decisão neste momento:** preservar todas as linhas até que seja possível justificar qualquer tratamento.


**4. Inconsistências textuais e frequência de produtos**

Os valores encontrados foram:

- `CL_GENERO`: `M` e `F`.
- `CL_SEG`: `A`, `B` e `C`.
- `PR_CAT`: `BEBIDAS`, `HIGIENE`, `ALIMENTOS`, `LIMPEZA`, `ACESSORIOS`, `PET` e `#N/D`.

O marcador `#N/D` apareceu **3.650 vezes em `PR_CAT`** e **3.650 vezes em `PR_NOME`**.

Esses marcadores não foram reconhecidos como valores ausentes pelo teste inicial `isna()`, pois estão registrados como texto. Será necessário avaliar seu tratamento na Sprint 2.

A consulta de frequência dos nomes de produtos apresentou `PRESUNTO COZIDO` na primeira posição, com **14.381 registros**.

Esse resultado indica maior frequência desse nome nas linhas da base, não necessariamente maior quantidade de unidades vendidas.

`ESCOVA DE DENTE` e `PAPINHA INFANTIL` apareceram empatados nas últimas posições dos dez produtos mais frequentes exibidos, com **7.346 registros cada**. Isso não significa que sejam os menos frequentes de toda a base.

### Consolidado do CP1.2

O diagnóstico permitiu identificar e quantificar possíveis problemas de qualidade sem modificar o arquivo original.

Os principais pontos encontrados foram:

1. Quatro colunas integralmente vazias.
2. Ausência de espaços e textos vazios nas cinco colunas textuais examinadas.
3. Existência de 96.553 repetições completas de linhas, ainda sem comprovação de erro.
4. Presença do marcador textual `#N/D` nas informações de produtos.
5. Possibilidade de investigar a frequência de produtos, a distribuição de compras, os perfis de clientes e os segmentos da base.

**Conclusão:** a análise inicial mostrou que nem toda repetição representa um problema e que nem todo marcador de informação indisponível é automaticamente identificado como valor ausente.

As decisões de limpeza serão justificadas na Sprint 2. As oportunidades de análise de negócio serão aprofundadas principalmente na Sprint 4.

# Fechamento da Sprint 1 — Leitura e diagnóstico

## Objetivo

Conhecer a estrutura da Base Varejo, identificar possíveis problemas de qualidade e compreender quais informações podem ser investigadas nas próximas etapas.

## CP1.1 — Importação e estrutura

A base foi importada com Python e Pandas por meio de `read_csv()`.

Os métodos `head()`, `shape`, `columns` e `info()` permitiram observar as primeiras linhas, as dimensões, os nomes das colunas, os tipos de dados e a quantidade de informações preenchidas.

Foram identificados **830.000 registros e 14 colunas físicas**, sendo dez nomeadas e quatro sem identificação.

## CP1.2 — Diagnóstico da qualidade

Foram utilizados recursos do Pandas para verificar valores ausentes, textos vazios, espaços, duplicatas, valores distintos e frequência de informações.

O diagnóstico identificou quatro colunas completamente vazias, 96.553 repetições completas de linhas e a presença do marcador `#N/D` nas informações de produtos.

Também foram encontrados 18.471 identificadores de compras, 1.000 de clientes e 229 de produtos distintos.

Esses resultados demonstraram que precisamos distinguir registros, compras, clientes e produtos antes de realizar qualquer exclusão ou interpretar indicadores.

## Oportunidades identificadas para as próximas análises

A investigação inicial levantou perguntas que podem contribuir para compreender melhor o comportamento registrado na base:

- Quais produtos e categorias aparecem com maior e menor frequência?
- Quais produtos estão associados ao maior número de compras distintas?
- Como os registros de compras se distribuem entre os gêneros `M` e `F`?
- Quais categorias são mais frequentes em cada segmento `A`, `B` e `C`?
- Como o número de compras e registros varia ao longo do tempo?
- Existem inconsistências na associação entre identificadores de clientes, compras e produtos?

Essas perguntas serão investigadas conforme os recursos disponíveis e o conteúdo estudado.

A base não apresenta campos explícitos de preço, custo, valor da venda ou quantidade de unidades. Portanto, não será possível calcular diretamente faturamento, lucro, margem ou volume de unidades vendidas.

Também será necessário confirmar o significado dos códigos de segmentação antes de atribuir características comerciais aos grupos `A`, `B` e `C`.

## Principais aprendizados

A Sprint 1 permitiu aplicar os conceitos iniciais de Python e Pandas na leitura de uma base real.

Além de conhecer os comandos, foi possível perceber a importância de interpretar os resultados e entender como os dados estão organizados.

Uma informação repetida não é necessariamente um erro. Da mesma forma, a presença de um código ou texto não garante que seu significado seja conhecido.

O diagnóstico deve preceder a limpeza, e toda alteração precisa de uma justificativa.

## Situação ao final da Sprint 1

Os dois checkpoints foram executados, e os resultados foram registrados.

A base original foi preservada, sem aplicação de tratamentos nesta Sprint.

## Próxima etapa — Sprint 2: Limpeza e padronização

Na Sprint 2 serão avaliados os problemas identificados, especialmente:

- As quatro colunas sem informações.
- Os marcadores `#N/D`.
- As linhas completamente repetidas.
- A consistência entre identificadores e seus respectivos registros.

As decisões deverão ser justificadas e acompanhadas por comparações antes e depois do tratamento.

As perguntas de negócio identificadas serão retomadas principalmente na Sprint 4, quando realizaremos filtros, estatísticas, agrupamentos e possíveis visualizações dos resultados.

# Sprint 2 — Limpeza e padronização dos dados

## CP2.1 — Investigação e decisões de tratamento

### Objetivo

Na Sprint 1, identificamos possíveis problemas de qualidade na Base Varejo. Agora precisamos avaliar quais situações realmente exigem correção e quais informações devem ser preservadas.

O objetivo deste checkpoint é **investigar e justificar as decisões antes de modificar os dados**.

### O que foi identificado anteriormente?

- Quatro colunas sem valores preenchidos.
- 96.553 repetições completas de linhas.
- 3.650 ocorrências do marcador `#N/D` em cada uma das colunas `PR_CAT` e `PR_NOME`.
- Necessidade de compreender melhor as relações entre compras, clientes e produtos.

### O que vamos investigar?

**1. Repetições de registros**

Vamos observar exemplos de linhas repetidas e verificar se existem elementos suficientes para considerar essas ocorrências erros.

**2. Relações entre os identificadores**

Vamos investigar se uma compra está associada a diferentes clientes ou datas e se os identificadores de clientes e produtos apresentam informações divergentes.

**3. Marcadores de informação indisponível**

Vamos verificar se as ocorrências de `#N/D` em `PR_CAT` e `PR_NOME` aparecem nos mesmos registros.

**4. Decisões de limpeza**

Ao final, registraremos quais problemas poderão ser corrigidos, quais informações precisam ser preservadas e quais limitações permanecerão documentadas.

### Conceitos utilizados

Aplicaremos métodos já estudados em Pandas, como `duplicated()`, `groupby()`, `nunique()`, `sum()` e `loc[]`.

**Dica de Ouro:** uma boa limpeza de dados não consiste em eliminar o maior número possível de registros. Consiste em melhorar a confiabilidade das informações sem perder dados válidos.

In [9]:
# CP2.1 — Investigação das linhas repetidas

# Identificar todas as ocorrências de linhas repetidas
repetidas = df_bruto.duplicated(keep=False)

print("Linhas pertencentes a grupos repetidos:")
print(repetidas.sum())

print("\nRepetições excedentes:")
print(df_bruto.duplicated().sum())

# Observar alguns exemplos
colunas_analise = [
    "DATA", "CO_ID", "CL_ID",
    "PR_ID", "PR_CAT", "PR_NOME"
]

display(
    df_bruto.loc[repetidas, colunas_analise].head(10)
)

Linhas pertencentes a grupos repetidos:
184330

Repetições excedentes:
96553

          DATA  CO_ID  CL_ID  PR_ID     PR_CAT             PR_NOME
3   01/02/2019   1000    534      4  ALIMENTOS             ABACAXI
7   01/02/2019   1000    534     11  ALIMENTOS              AZEITE
14  01/02/2019   1000    534     13  ALIMENTOS              BANANA
15  01/02/2019   1000    534    218  ALIMENTOS  BIFE DE COXAO MOLE
19  01/02/2019   1000    534     13  ALIMENTOS              BANANA
22  01/02/2019   1000    534     69    BEBIDAS  REFRIGERANTE LIMaO
34  01/02/2019   1000    534    225  ALIMENTOS                ATUM
40  01/02/2019   1000    534      4  ALIMENTOS             ABACAXI
46  01/02/2019   1000    534     11  ALIMENTOS              AZEITE
49  01/02/2019   1000    534     69    BEBIDAS  REFRIGERANTE LIMaO

In [10]:
# CP2.1 — Consistência das informações

verificacoes = [
    ("Compras com mais de um cliente",
     "CO_ID", "CL_ID"),

    ("Compras com mais de uma data",
     "CO_ID", "DATA"),

    ("Clientes com mais de um gênero registrado",
     "CL_ID", "CL_GENERO"),

    ("Clientes com mais de um segmento",
     "CL_ID", "CL_SEG"),

    ("Produtos com mais de um nome",
     "PR_ID", "PR_NOME"),

    ("Produtos com mais de uma categoria",
     "PR_ID", "PR_CAT")
]

for descricao, identificador, campo in verificacoes:

    quantidades = (
        df_bruto.groupby(identificador)[campo].nunique()
    )

    divergencias = (quantidades > 1).sum()

    print(descricao, ":", divergencias)

Compras com mais de um cliente : 0
Compras com mais de uma data : 0
Clientes com mais de um gênero registrado : 0
Clientes com mais de um segmento : 0
Produtos com mais de um nome : 0
Produtos com mais de uma categoria : 0

In [11]:
# CP2.1 — Investigação dos marcadores #N/D

categoria_sem_dado = (
    df_bruto["PR_CAT"].astype("string").str.strip().eq("#N/D")
)

nome_sem_dado = (
    df_bruto["PR_NOME"].astype("string").str.strip().eq("#N/D")
)

print("Marcadores em PR_CAT:", categoria_sem_dado.sum())
print("Marcadores em PR_NOME:", nome_sem_dado.sum())

print(
    "Marcadores nas duas colunas da mesma linha:",
    (categoria_sem_dado & nome_sem_dado).sum()
)

print(
    "Registros com marcador em pelo menos uma coluna:",
    (categoria_sem_dado | nome_sem_dado).sum()
)

display(
    df_bruto.loc[
        categoria_sem_dado | nome_sem_dado,
        ["CO_ID", "PR_ID", "PR_CAT", "PR_NOME"]
    ].head(10)
)

Marcadores em PR_CAT: 3650
Marcadores em PR_NOME: 3650
Marcadores nas duas colunas da mesma linha: 3650
Registros com marcador em pelo menos uma coluna: 3650

      CO_ID  PR_ID PR_CAT PR_NOME
82     1078    107   #N/D    #N/D
223    1103    107   #N/D    #N/D
640    1482    107   #N/D    #N/D
857    1683    107   #N/D    #N/D
917    1793    107   #N/D    #N/D
1185   2151    107   #N/D    #N/D
1273   2224    107   #N/D    #N/D
1303   2311    107   #N/D    #N/D
1325   2311    107   #N/D    #N/D
1385   2327    107   #N/D    #N/D

In [12]:
# CP2.1 — Verificações complementares

# Identificar os códigos de produto com marcador #N/D
codigos_sem_dado = df_bruto.loc[
    categoria_sem_dado | nome_sem_dado,
    "PR_ID"
]

print("Códigos de produto associados a #N/D:")
display(codigos_sem_dado.value_counts())

# Verificar se esses códigos possuem outros nomes ou categorias
print("\nInformações disponíveis para esses códigos:")

display(
    df_bruto.loc[
        df_bruto["PR_ID"].isin(codigos_sem_dado.unique()),
        ["PR_ID", "PR_CAT", "PR_NOME"]
    ].drop_duplicates()
)

# Completar a conferência dos atributos do cliente
print("\nConsistência de outros campos do cliente:")

for coluna in ["CL_EC", "CL_FHL"]:

    divergencias = (
        df_bruto.groupby("CL_ID")[coluna]
        .nunique()
        .gt(1)
        .sum()
    )

    print(coluna, "- Clientes com valores diferentes:", divergencias)

Códigos de produto associados a #N/D:

PR_ID
107    3650
Name: count, dtype: int64

Informações disponíveis para esses códigos:

    PR_ID PR_CAT PR_NOME
82    107   #N/D    #N/D

Consistência de outros campos do cliente:
CL_EC - Clientes com valores diferentes: 0
CL_FHL - Clientes com valores diferentes: 0

### Interpretação dos resultados do CP2.1

**1. Repetições completas**

A investigação identificou **184.330 linhas pertencentes a grupos de registros repetidos**, das quais **96.553 são ocorrências excedentes**.

O método `duplicated(keep=False)` permitiu identificar todas as linhas pertencentes a grupos repetidos, incluindo suas primeiras ocorrências. Já `duplicated()` contabilizou somente as repetições adicionais.

Nos exemplos apresentados, encontramos registros com informações idênticas:

| Linhas | Produto | Identificador da compra (`CO_ID`) | Identificador do cliente (`CL_ID`) |
|---|---|---:|---:|
| 3 e 40 | ABACAXI | 1000 | 534 |
| 7 e 46 | AZEITE | 1000 | 534 |
| 14 e 19 | BANANA | 1000 | 534 |
| 22 e 49 | REFRIGERANTE LIMaO | 1000 | 534 |

Essas ocorrências demonstram que existem linhas completamente repetidas, considerando todos os campos da base.

**Interpretação:** apesar da repetição dos registros, ainda não podemos afirmar que todas essas ocorrências sejam erros.

Uma compra pode conter mais de uma unidade do mesmo produto. Como a base não apresenta uma coluna de quantidade nem um identificador individual de item, não é possível distinguir com segurança uma repetição indevida de uma ocorrência legítima.

Por esse motivo, as linhas repetidas serão preservadas até que exista uma justificativa suficiente para sua eventual exclusão.

**2. Consistência dos identificadores**

A investigação utilizou `groupby()` e `nunique()` para verificar se um mesmo identificador apresenta informações diferentes em determinados campos.

As seis verificações iniciais apresentaram resultado zero:

| Verificação | Divergências encontradas |
|---|---:|
| Compras associadas a mais de um cliente | 0 |
| Compras associadas a mais de uma data | 0 |
| Clientes com mais de um gênero registrado | 0 |
| Clientes com mais de um segmento | 0 |
| Produtos com mais de um nome | 0 |
| Produtos com mais de uma categoria | 0 |

A verificação complementar também examinou outros dois campos associados aos clientes:

| Verificação complementar | Divergências encontradas |
|---|---:|
| Clientes com valores diferentes em `CL_EC` | 0 |
| Clientes com valores diferentes em `CL_FHL` | 0 |

**Interpretação:** não foram identificadas contradições nas oito relações examinadas.

Por exemplo, o mesmo cliente pode realizar diferentes compras e aparecer várias vezes na base. Isso não significa que exista duplicidade indevida em seu cadastro.

Da mesma maneira, uma compra pode conter diferentes produtos, mantendo o mesmo identificador de cliente e a mesma data.

Os resultados indicam que os identificadores apresentam informações consistentes nos campos analisados.

Entretanto, essa consistência não comprova que todos os cadastros estejam corretos nem elimina a possibilidade de outros problemas de qualidade.

Também não permite identificar o significado dos códigos `CL_EC`, `CL_FHL` ou dos segmentos `A`, `B` e `C`, pois essas definições dependem de informações complementares sobre a base.

**3. Marcadores `#N/D`**

A investigação identificou **3.650 ocorrências do marcador `#N/D` na coluna `PR_CAT`** e **3.650 ocorrências na coluna `PR_NOME`**.

O cruzamento mostrou que os marcadores aparecem simultaneamente nas mesmas 3.650 linhas, não representando dois conjuntos diferentes de registros.

Na verificação complementar, utilizamos `value_counts()` para identificar os códigos de produto associados a essas ocorrências.

**Resultado:** todas as 3.650 ocorrências estão associadas exclusivamente ao identificador de produto `107`.

A consulta dos valores distintos de nome e categoria desse produto apresentou apenas:

| `PR_ID` | `PR_CAT` | `PR_NOME` |
|---|---|---|
| 107 | `#N/D` | `#N/D` |

**Interpretação:** o produto identificado pelo código `107` possui registros na base, mas seu nome e sua categoria não estão disponíveis.

Como não foram encontrados outros nomes ou categorias associados a esse código, não é possível recuperar essas informações com segurança utilizando apenas os dados existentes.

O marcador `#N/D` representa uma informação indisponível e deverá receber um tratamento justificado, sem inventar o nome ou a categoria do produto.

Também é importante preservar os registros associados ao produto `107`, pois a ausência de sua identificação textual não significa que suas ocorrências devam ser excluídas.

### Quadro de decisões preliminares de tratamento

| Situação identificada | Encaminhamento | Justificativa |
|---|---|---|
| Quatro colunas completamente vazias | Remover da cópia de trabalho | Não apresentam valores preenchidos nem informações úteis identificadas |
| Marcadores `#N/D` em `PR_CAT` e `PR_NOME` | Avaliar padronização como informação não disponível | Preservar os registros sem atribuir valores desconhecidos |
| Produto `107` sem nome e categoria disponíveis | Preservar o identificador e seus registros | Não existe informação confiável na base para recuperar os textos |
| Linhas completamente repetidas | Preservar neste momento | Não há evidência suficiente para classificar todas as repetições como erros |
| Relações entre identificadores e atributos | Manter as informações examinadas | Não foram identificadas contradições nas oito verificações |

### Consolidado do CP2.1

O checkpoint permitiu aprofundar a investigação dos possíveis problemas de qualidade identificados na Sprint 1.

A análise confirmou a existência de linhas completamente repetidas, mas demonstrou que sua exclusão exige cautela, pois não temos informações suficientes para distinguir todas as repetições legítimas de possíveis erros.

As verificações de consistência também mostraram que os identificadores de compras, clientes e produtos mantêm relações coerentes nos oito campos examinados.

Além disso, identificamos que as 3.650 ocorrências do marcador `#N/D` correspondem ao produto `107`, que não possui nome ou categoria conhecidos na base.

**Principais aprendizados:**

- A repetição de um registro não significa necessariamente erro.
- Identificadores podem aparecer diversas vezes sem representar duplicidade de cadastro.
- Informações desconhecidas não devem ser substituídas por valores inventados.
- A ausência de dados em uma coluna não exige a exclusão dos registros correspondentes.
- Toda decisão de limpeza precisa estar apoiada nas evidências encontradas.

**Conclusão do CP2.1**

As investigações forneceram elementos para orientar o tratamento dos dados.

A remoção das quatro colunas integralmente vazias é uma medida justificável. Os marcadores `#N/D` poderão ser padronizados, desde que sua condição de informação desconhecida seja preservada.

As repetições completas permanecerão na base enquanto não houver evidência suficiente para justificar sua exclusão.

**Próxima etapa — CP2.2:** aplicar as decisões justificadas em uma cópia do DataFrame, preservar a base original e comparar os resultados antes e depois da limpeza.

## CP2.2 — Aplicação e conferência da limpeza

### Objetivo

Aplicar os tratamentos definidos no CP2.1 sem alterar o conjunto de dados original.

Para isso, trabalharemos com uma cópia do DataFrame.

Após cada tratamento, compararemos a situação inicial com o resultado obtido, verificando se as mudanças foram adequadas e se informações importantes foram preservadas.

### Etapas

1. Criar uma cópia da base original.
2. Aplicar apenas os tratamentos justificados.
3. Verificar a quantidade de linhas e colunas antes e depois.
4. Conferir os valores ausentes, os marcadores textuais e as repetições.
5. Registrar os efeitos e as limitações das decisões.

**Dica de Ouro:** preservar `df_bruto` facilita conferir as alterações e corrigir uma decisão sem perder os dados originais.

In [13]:
# CP2.2 — Limpeza e conferência dos dados

# 1. Criar uma cópia da base original
df_trabalho = df_bruto.copy()

# 2. Remover as quatro colunas vazias
df_trabalho = df_trabalho.drop(
    columns=[
        "Unnamed: 10",
        "Unnamed: 11",
        "Unnamed: 12",
        "Unnamed: 13"
    ]
)

# 3. Padronizar os textos de informação desconhecida
df_trabalho["PR_CAT"] = df_trabalho["PR_CAT"].replace(
    "#N/D", "NÃO INFORMADA"
)

df_trabalho["PR_NOME"] = df_trabalho["PR_NOME"].replace(
    "#N/D", "NÃO INFORMADO"
)

# 4. Comparar antes e depois
print("Dimensões antes:", df_bruto.shape)
print("Dimensões depois:", df_trabalho.shape)

print("\nRepetições antes:", df_bruto.duplicated().sum())
print("Repetições depois:", df_trabalho.duplicated().sum())

print("\nValores ausentes após a limpeza:")
display(df_trabalho.isna().sum())

# 5. Conferir as informações padronizadas
print("\nMarcadores #N/D restantes:")
print("PR_CAT:", df_trabalho["PR_CAT"].eq("#N/D").sum())
print("PR_NOME:", df_trabalho["PR_NOME"].eq("#N/D").sum())

print("\nInformações padronizadas:")
print("Categoria não informada:",
      df_trabalho["PR_CAT"].eq("NÃO INFORMADA").sum())
print("Produto não informado:",
      df_trabalho["PR_NOME"].eq("NÃO INFORMADO").sum())

# 6. Conferir se o produto 107 foi preservado
print("\nRegistros do produto 107:")
print("Antes:", df_bruto["PR_ID"].eq(107).sum())
print("Depois:", df_trabalho["PR_ID"].eq(107).sum())

# 7. Visualizar os dados tratados
print("\nPrimeiras linhas após o tratamento:")
display(df_trabalho.head())

Dimensões antes: (830000, 14)
Dimensões depois: (830000, 10)

Repetições antes: 96553
Repetições depois: 96553

Valores ausentes após a limpeza:

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

Marcadores #N/D restantes:
PR_CAT: 0
PR_NOME: 0

Informações padronizadas:
Categoria não informada: 3650
Produto não informado: 3650

Registros do produto 107:
Antes: 3650
Depois: 3650

Primeiras linhas após o tratamento:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

### Interpretação dos resultados do CP2.2

**1. Preservação dos dados originais**

A limpeza foi realizada sobre uma cópia do DataFrame original, utilizando `df_bruto.copy()`.

A cópia, identificada como `df_trabalho`, permitiu aplicar os tratamentos sem modificar os dados armazenados em `df_bruto`.

Essa separação é importante porque possibilita comparar as informações antes e depois das alterações.

**2. Tratamento das colunas sem informações**

Foram removidas da cópia as quatro colunas identificadas como `Unnamed: 10`, `Unnamed: 11`, `Unnamed: 12` e `Unnamed: 13`.

A decisão foi baseada no diagnóstico anterior, que identificou 830.000 valores ausentes em cada uma dessas colunas, correspondentes à totalidade dos registros.

Após a remoção, a base passou de **14 para 10 colunas**, mantendo seus **830.000 registros**.

**Interpretação:** a remoção eliminou campos sem conteúdo, tornando a estrutura da tabela mais clara, sem excluir registros de compras, clientes ou produtos.

**3. Padronização dos marcadores de informação indisponível**

Os marcadores `#N/D` foram padronizados nas seguintes colunas:

| Coluna | Marcador original | Novo rótulo |
|---|---|---|
| `PR_CAT` | `#N/D` | `NÃO INFORMADA` |
| `PR_NOME` | `#N/D` | `NÃO INFORMADO` |

Antes da limpeza, cada coluna apresentava 3.650 ocorrências de `#N/D`.

Após o tratamento, o marcador original deixou de aparecer, e os novos rótulos passaram a representar as mesmas 3.650 ocorrências em cada coluna.

**Interpretação:** a padronização facilitou a identificação de informações indisponíveis, sem inventar nomes ou categorias. O conteúdo continua desconhecido, mas agora está representado por uma descrição mais compreensível.

**4. Preservação das repetições completas**

A base apresentava 96.553 repetições excedentes antes do tratamento.

Após a limpeza, essa quantidade permaneceu inalterada.

Essa manutenção foi intencional. Como ainda não existem informações suficientes para distinguir todas as repetições legítimas de possíveis erros, não foi aplicada a exclusão automática com `drop_duplicates()`.

O produto identificado pelo código `107` também teve seus 3.650 registros preservados.

**Interpretação:** a limpeza tratou problemas comprovados sem eliminar registros cuja exclusão poderia representar perda de informação.

**5. Comparação antes e depois**

| Indicador | Antes | Depois |
|---|---:|---:|
| Registros | 830.000 | 830.000 |
| Colunas | 14 | 10 |
| Repetições excedentes | 96.553 | 96.553 |
| Marcadores `#N/D` em `PR_CAT` | 3.650 | 0 |
| Marcadores `#N/D` em `PR_NOME` | 3.650 | 0 |
| Registros do produto `107` | 3.650 | 3.650 |

A conferência com `isna().sum()` também mostrou que as dez colunas restantes não apresentam valores ausentes reconhecidos pelo Pandas.

Isso não significa que todas as informações estejam disponíveis: existem 3.650 registros com nome e categoria do produto desconhecidos, agora identificados por rótulos padronizados.

### Consolidado do CP2.2

O tratamento realizado permitiu organizar a estrutura da base e padronizar informações indisponíveis, mantendo os registros originais necessários para as próximas análises.

As alterações foram realizadas sobre uma cópia do DataFrame, preservando a possibilidade de comparação com os dados recebidos.

A remoção das quatro colunas vazias e a padronização dos marcadores textuais foram baseadas nos problemas comprovados durante o diagnóstico.

As repetições completas foram mantidas por não haver evidências suficientes para justificar sua exclusão.

**Conclusão do CP2.2:** os tratamentos planejados foram aplicados e os resultados conferidos. A base de trabalho passou a conter 830.000 registros e dez colunas, com os marcadores de informação indisponível padronizados.

**Próxima etapa:** consolidar os resultados da Sprint 2 e avançar para a organização das funções na Sprint 3.

# Fechamento da Sprint 2 — Limpeza e padronização

## Objetivo

Investigar os problemas identificados na Base Varejo e aplicar tratamentos justificados, preservando as informações que não poderiam ser classificadas como incorretas.

## CP2.1 — Investigação e decisões

Foram encontradas 96.553 repetições excedentes, quatro colunas completamente vazias e 3.650 registros do produto `107` com nome e categoria indicados como `#N/D`. As oito verificações de consistência entre identificadores não apontaram divergências.

Foi decidido remover as colunas vazias e padronizar as informações desconhecidas. As linhas repetidas foram mantidas porque não havia evidência suficiente para afirmar que eram erros.

## CP2.2 — Aplicação e conferência

O tratamento foi realizado em `df_trabalho`, uma cópia de `df_bruto`, utilizando `copy()`, `drop()` e `replace()`.

A comparação confirmou que os 830.000 registros foram preservados, enquanto a quantidade de colunas passou de 14 para 10. Os marcadores `#N/D` foram substituídos por rótulos de informação não disponível, sem excluir os 3.650 registros do produto `107`. As 96.553 repetições excedentes também permaneceram na base.

## Principais aprendizados

A limpeza de dados não consiste apenas em excluir registros repetidos ou incompletos. Antes de alterar a base, é necessário investigar os problemas e justificar cada decisão.

Trabalhar sobre uma cópia permitiu preservar os dados originais e conferir o resultado das alterações, evitando perdas indevidas de informação.

## Limitações

Não foi possível determinar se todas as linhas repetidas representam erros, pois faltam informações que diferenciem ocorrências legítimas de duplicações indevidas.

Também não foi possível recuperar o nome e a categoria do produto `107`. Para isso, seria necessária uma fonte confiável, como um cadastro de produtos. Por enquanto, esses dados continuam identificados como não informados.

## Situação ao final da Sprint 2

A base de trabalho ficou com **830.000 registros e dez colunas**, com as informações desconhecidas padronizadas e sem exclusão de linhas. O DataFrame original foi preservado.

Na Sprint 3, o tratamento e a geração de resumos serão organizados em funções com parâmetros e retorno, conforme o enunciado.

# Sprint 3 — Funções e organização

## CP3.1 — Compreendendo a função de tratamento

### Objetivo

Nas sprints anteriores, aprendemos a importar, investigar e limpar uma base de dados com Pandas.

Agora vamos organizar parte desse trabalho em funções, para que os mesmos procedimentos possam ser utilizados novamente sem precisar reescrever todos os comandos.

### O que é uma função?

Uma função é um conjunto de instruções criado para realizar uma tarefa específica.

Em Python, utilizamos:

- `def` para definir a função;
- **parâmetro** para receber a informação que será utilizada;
- `return` para devolver o resultado do processamento.

Uma função não precisa modificar diretamente a base original. Podemos receber um DataFrame, criar uma cópia, realizar os tratamentos e devolver a versão tratada.

### Aplicação no mini-projeto

Na Sprint 2, realizamos a limpeza com comandos executados diretamente no notebook.

Na Sprint 3, o objetivo é compreender como reunir esses tratamentos em uma função reutilizável.

**Dica de Ouro:** `print()` mostra uma informação na tela; `return` devolve um resultado que poderá ser armazenado em uma variável e utilizado nas próximas etapas.

In [14]:
# CP3.1 — Organizar o tratamento em uma função

# Criar uma função que recebe uma tabela
def tratar_dados(tabela):

    # Preservar a tabela recebida
    tratado = tabela.copy()

    # PASSO 1 — Remover as quatro colunas vazias
    tratado = tratado.drop(
        columns=[
            "Unnamed: 10",
            "Unnamed: 11",
            "Unnamed: 12",
            "Unnamed: 13"
        ]
    )

    # PASSO 2 — Padronizar a categoria desconhecida
    tratado["PR_CAT"] = tratado["PR_CAT"].replace(
        "#N/D", "NÃO INFORMADA"
    )

    # PASSO 3 — Padronizar o nome desconhecido
    tratado["PR_NOME"] = tratado["PR_NOME"].replace(
        "#N/D", "NÃO INFORMADO"
    )

    # Devolver a tabela tratada
    return tratado


# CONFERÊNCIA — Chamar a função
df_funcao = tratar_dados(df_bruto)

print("Dimensões:", df_funcao.shape)

print(
    "Mesmo resultado do CP2.2:",
    df_funcao.equals(df_trabalho)
)

print("\nPrimeiras linhas da tabela tratada:")
display(df_funcao.head())

Dimensões: (830000, 10)
Mesmo resultado do CP2.2: True

Primeiras linhas da tabela tratada:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO

## CP3.2 — Função de resumo da Base Varejo

### Objetivo

Organizar em uma função reutilizável o resumo da base tratada, preservando a distinção entre registros e identificadores distintos.

### Procedimento

A função `gerar_resumo(tabela)` recebe o DataFrame e retorna um dicionário com quatro indicadores: quantidade de registros, compras distintas (`CO_ID`), clientes distintos (`CL_ID`) e produtos distintos (`PR_ID`). Em seguida, a função é chamada com `df_funcao`, conforme o código apresentado abaixo.

In [15]:
# CP3.2 — Função de resumo da Base Varejo

def gerar_resumo(tabela):

    resumo = {
        "registros": len(tabela),
        "compras_distintas": tabela["CO_ID"].nunique(),
        "clientes_distintos": tabela["CL_ID"].nunique(),
        "produtos_distintos": tabela["PR_ID"].nunique()
    }

    return resumo


# Chamar a função com a base tratada
resumo_varejo = gerar_resumo(df_funcao)

print(resumo_varejo)

{'registros': 830000, 'compras_distintas': 18471, 'clientes_distintos': 1000, 'produtos_distintos': 229}

# Fechamento da Sprint 3 — Funções e organização

## Funções desenvolvidas

Foram criadas e executadas duas funções com parâmetros e retorno:

- `tratar_dados(tabela)`: aplica os tratamentos justificados na Sprint 2. A comparação com o resultado anterior confirmou igualdade (`True`).
- `gerar_resumo(tabela)`: recebe a base tratada e devolve um dicionário com contagens de registros, compras, clientes e produtos distintos.

## Resultados do resumo

| Indicador | Resultado |
|---|---:|
| Registros | 830.000 |
| Compras distintas | 18.471 |
| Clientes distintos | 1.000 |
| Produtos distintos | 229 |

Essas contagens representam linhas e identificadores distintos, não quantidades de unidades vendidas nem faturamento.

## Principais aprendizados

Aprendi que um parâmetro permite fornecer dados a uma função, enquanto `return` devolve o resultado para utilização posterior.

Organizar os comandos em funções reduz repetições e facilita a leitura, a conferência e o reaproveitamento do código.

## Conclusão

A primeira função reorganizou a limpeza já realizada e reproduziu o resultado anterior. A segunda gerou um resumo da Base Varejo.

Ambas foram executadas e conferidas, preservando os dados originais.

## Próxima etapa

Na Sprint 4, serão estudados filtros, estatísticas básicas e agrupamentos, respeitando os limites das informações disponíveis.

# Sprint 4 — Análise dos dados

## CP4.1 — Aplicação de um filtro

### Objetivo

Utilizar a base tratada na Sprint 3 para selecionar registros que atendam a uma condição e compreender o resultado.

### Pergunta de análise

Quantos registros estão associados a uma determinada categoria de produto?

Para responder, vamos utilizar a coluna `PR_CAT` e selecionar uma categoria existente na Base Varejo.

### Como interpretar

O filtro permite visualizar apenas os registros que atendem à condição escolhida.

A quantidade encontrada representa **linhas da base**, e não necessariamente compras distintas ou unidades vendidas. Essa diferença deverá ser considerada na interpretação.

In [16]:
# CP4.1 — Filtro da categoria BEBIDAS

filtrado = df_funcao[df_funcao["PR_CAT"] == "BEBIDAS"]

print("Quantidade de registros:", len(filtrado))

display(filtrado.head())

Quantidade de registros: 43299

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS
9,01/02/2019,1000,534,M,4,1,C,198,BEBIDAS,ENERGETICO
22,01/02/2019,1000,534,M,4,1,C,69,BEBIDAS,REFRIGERANTE LIMaO
23,01/02/2019,1000,534,M,4,1,C,143,BEBIDAS,REFRIGERANTE GUARANA

### Interpretação dos resultados do CP4.1

O filtro identificou **43.299 registros** associados à categoria `BEBIDAS`.

Esse resultado representa a quantidade de linhas dessa categoria na Base Varejo, não necessariamente o número de compras distintas ou de unidades vendidas.

Como uma mesma compra pode aparecer em várias linhas e a base não possui uma coluna de quantidade, não é possível determinar o total de unidades comercializadas apenas por essa contagem.

## CP4.2 — Agrupamentos com `groupby()`

### Objetivo

Agrupar os registros da Base Varejo para comparar categorias de produtos e segmentos de clientes.

### Investigação 1 — Registros por categoria

Identificar quantas linhas da base pertencem a cada categoria de produto, utilizando `PR_CAT`.

### Investigação 2 — Compras distintas por segmento

Identificar quantos códigos de compra diferentes existem em cada segmento, utilizando `CL_SEG` e `CO_ID`.

### Cuidados na interpretação

- `.size()` conta as linhas de cada grupo.
- `.nunique()` conta os valores diferentes de uma coluna dentro de cada grupo.
- A quantidade de registros não deve ser confundida com compras distintas, unidades vendidas ou faturamento.

Os resultados serão interpretados após a execução dos agrupamentos.

In [17]:
# CP4.2 — Agrupamentos da Base Varejo

# 1. Contar registros por categoria de produto
print("Registros por categoria:")

registros_por_categoria = (
    df_funcao.groupby("PR_CAT")
    .size()
    .sort_values(ascending=False)
)

display(registros_por_categoria)


# 2. Contar compras distintas por segmento
print("Compras distintas por segmento:")

compras_por_segmento = (
    df_funcao.groupby("CL_SEG")["CO_ID"]
    .nunique()
    .sort_values(ascending=False)
)

display(compras_por_segmento)

Registros por categoria:

PR_CAT
ALIMENTOS        434767
HIGIENE          155574
LIMPEZA          145754
BEBIDAS           43299
PET               32399
ACESSORIOS        14557
NÃO INFORMADA      3650
dtype: int64

Compras distintas por segmento:

CL_SEG
B    11843
C     5136
A     1492
Name: CO_ID, dtype: int64

### Interpretação dos resultados do CP4.2

**Agrupamento por categoria:** A categoria com mais registros foi **ALIMENTOS**, com **434.767 linhas**. Esse resultado mede a quantidade de registros associados a cada categoria de produto na Base Varejo.

**Agrupamento por segmento:** O segmento com mais compras distintas foi **B**, com **11.843 códigos de compra diferentes**. Esse resultado mede a quantidade de compras distintas associadas a cada segmento, considerando os valores únicos de `CO_ID`.

**Diferença entre as métricas:** O método `.size()` conta todas as linhas existentes em cada grupo, mesmo quando um código de compra aparece repetidamente. Já o método `.nunique()` conta somente os valores distintos de uma coluna. Neste caso, ele identifica quantos códigos de compra (`CO_ID`) diferentes existem em cada segmento.

Por isso, uma mesma compra pode contribuir com várias linhas para a contagem de registros, mas será contabilizada apenas uma vez na contagem de compras distintas do seu segmento.

**Limitação:** Esses resultados não permitem determinar diretamente quantas unidades foram vendidas nem qual foi o faturamento.

A Base Varejo utilizada neste projeto não possui colunas de quantidade vendida, preço ou valor da venda. Portanto, as análises realizadas representam contagens de registros e identificadores distintos, não volumes físicos ou valores financeiros.

Além disso, os códigos dos segmentos (`A`, `B` e `C`) foram mantidos conforme a base original, sem atribuir significados econômicos não confirmados.

## CP4.3 — Estatísticas básicas

### Objetivo

Calcular e interpretar estatísticas básicas de uma medida numérica significativa, utilizando os dados tratados da Base Varejo.

Serão analisados quatro indicadores:

- Contagem de valores válidos;
- Média;
- Valor mínimo;
- Valor máximo.

### Medida analisada

**Quantidade de códigos de produtos distintos por compra.**

Como a Base Varejo não possui informações de quantidade vendida, preço ou valor de compra, foi utilizada uma medida numérica derivada dos registros existentes.

Para cada código de compra (`CO_ID`), a análise identifica quantos códigos de produtos diferentes (`PR_ID`) aparecem nos registros associados àquela compra.

Essa informação permite investigar a **diversidade de tipos de produtos por compra**, sem confundi-la com a quantidade física de unidades comercializadas.

### Procedimento

A análise utiliza `groupby()` e `.nunique()` para construir a medida por compra. Em seguida, são aplicados os métodos `.count()`, `.mean()`, `.min()` e `.max()` sobre a série numérica obtida.

### Limitação metodológica

A medida foi construída a partir da contagem de identificadores distintos; ela não representa uma coluna numérica originalmente disponível na base.

Embora seja quantitativa e tenha significado analítico, sua aceitação como atendimento à exigência literal de uma coluna numérica adequada depende da avaliação da instituição.

In [18]:
# CP4.3 — Estatísticas básicas

tipos_por_compra = (
    df_funcao.groupby("CO_ID")["PR_ID"]
    .nunique()
)

contagem = tipos_por_compra.count()
media = tipos_por_compra.mean()
minimo = tipos_por_compra.min()
maximo = tipos_por_compra.max()

print("Contagem válida:", contagem, "compras")
print("Média:", round(media, 2), "tipos de produtos por compra")
print("Mínimo:", minimo, "tipo(s) de produto por compra")
print("Máximo:", maximo, "tipo(s) de produto por compra")

Contagem válida: 18471 compras
Média: 39.71 tipos de produtos por compra
Mínimo: 1 tipo(s) de produto por compra
Máximo: 81 tipo(s) de produto por compra

### Interpretação dos resultados do CP4.3

A análise considera a quantidade de códigos de produtos diferentes (`PR_ID`) presentes em cada compra (`CO_ID`).

Foram analisadas **18.471 compras**, com média de **39,71 tipos de produtos distintos por compra**.

O valor mínimo observado foi de **1 tipo de produto por compra**, enquanto o máximo foi de **81 tipos distintos em uma compra**.

Esses resultados representam a variedade de produtos associados às compras, e não a quantidade física de unidades vendidas ou o faturamento.


## CP4.4 — Perfil dos clientes por gênero

### Pergunta de investigação

Como os grupos identificados pelos códigos M e F se distribuem em clientes distintos, compras distintas e registros da Base Varejo?

### Unidade de análise

A investigação considera três unidades diferentes:

- **Cliente distinto (`CL_ID`):** identifica cada cliente uma única vez dentro do seu grupo de gênero.
- **Compra distinta (`CO_ID`):** identifica cada compra uma única vez dentro do grupo de gênero associado ao cliente.
- **Registro:** representa uma linha da base de dados, que pode conter uma ocorrência de produto associada a determinada compra.

### Objetivo do procedimento

Comparar clientes distintos, compras distintas e registros ajuda a compreender a composição da base em níveis diferentes.

A contagem de clientes informa quantas pessoas distintas existem em cada grupo. A contagem de compras mostra quantas operações de compra distintas estão associadas a esses clientes. Já a contagem de registros revela a quantidade de ocorrências documentadas na base.

Essas medidas não são equivalentes. Um cliente pode estar associado a várias compras, e uma compra pode aparecer em diversas linhas, inclusive com repetições de códigos de produtos.

Portanto, uma quantidade maior de registros não comprova, por si só, maior quantidade física de produtos vendidos ou maior valor gasto.

A comparação será realizada por meio de agrupamentos, contagens de valores distintos e conferência dos totais.

In [19]:
# CP4.4 — Perfil dos clientes por gênero

resumo_genero = (
    df_funcao
    .groupby("CL_GENERO")
    .agg(
        clientes_distintos=("CL_ID", "nunique"),
        compras_distintas=("CO_ID", "nunique"),
        registros=("CL_ID", "size")
    )
    .reset_index()
)

display(resumo_genero)

print("Clientes distintos:", resumo_genero["clientes_distintos"].sum())
print("Compras distintas:", resumo_genero["compras_distintas"].sum())
print("Registros:", resumo_genero["registros"].sum())

  CL_GENERO  clientes_distintos  compras_distintas  registros
0         F                 519               9615     432576
1         M                 481               8856     397424

Clientes distintos: 1000
Compras distintas: 18471
Registros: 830000

### Interpretação dos resultados do CP4.4

A comparação considera três indicadores: clientes distintos, compras distintas e registros, utilizando os respectivos totais como denominadores.

**Distribuição observada**

Os resultados mostram uma distribuição relativamente equilibrada entre os grupos F e M, com participação ligeiramente maior do grupo F nos três indicadores analisados.

Em relação aos clientes distintos, o grupo F possui 519 clientes, correspondendo a 51,90% do total de 1.000 clientes, enquanto o grupo M possui 481 clientes, equivalente a 48,10%.

Nas compras distintas, o grupo F apresenta 9.615 compras, representando aproximadamente 52,05% das 18.471 compras identificadas. O grupo M possui 8.856 compras, correspondendo a aproximadamente 47,95%.

Considerando todos os registros da base, o grupo F concentra 432.576 registros, ou aproximadamente 52,12% do total de 830.000 registros. O grupo M reúne 397.424 registros, equivalentes a aproximadamente 47,88%.

Portanto, o grupo F apresenta participação um pouco superior ao grupo M em clientes, compras e registros. A diferença é pequena e permanece próxima de quatro pontos percentuais em todos os indicadores, indicando que a composição da base está relativamente equilibrada entre os dois grupos.

**Interpretação das métricas**

A contagem de clientes distintos identifica quantas pessoas diferentes estão representadas em cada grupo.

A contagem de compras distintas identifica quantas operações de compra estão associadas aos clientes desses grupos.

A contagem de registros considera todas as ocorrências presentes na base, inclusive quando uma compra aparece em várias linhas.

Esses indicadores representam dimensões diferentes e não devem ser interpretados como equivalentes.

**Limitações da análise**

Os resultados permitem identificar como clientes, compras e registros estão distribuídos, mas não explicam, isoladamente, as causas das diferenças observadas.

Uma quantidade maior de registros não comprova maior quantidade física de produtos vendidos ou maior valor gasto.

Da mesma forma, mais compras totais em um grupo não demonstram automaticamente maior frequência de compras por cliente.

Portanto, conclusões sobre preferências, comportamento ou consumo monetário exigiriam evidências adicionais.


## CP4.5 — Distribuição das categorias de produtos por gênero

### Pergunta de investigação

Como os registros das diferentes categorias de produtos estão distribuídos entre os grupos de gênero M e F?

### Objetivo

Na investigação anterior, foram examinados clientes, compras distintas e registros por gênero.

Agora, o objetivo é aprofundar essa análise por meio do cruzamento entre `PR_CAT` e `CL_GENERO`.

Esse cruzamento permite observar como as categorias de produtos se distribuem dentro de cada grupo, em vez de analisar gênero e categoria separadamente.

### Unidade de análise

A unidade analisada será o **registro da Base Varejo**, contado em cada combinação de categoria de produto e código de gênero.

A contagem corresponde às ocorrências registradas, e não necessariamente à quantidade física de unidades vendidas.

### Procedimento

Serão considerados:

- O número absoluto de registros de cada categoria em cada grupo de gênero.
- O total de registros de cada grupo.
- A participação percentual de cada categoria dentro de seu respectivo grupo.
- A conferência dos totais utilizados nos cálculos.

A comparação percentual deve utilizar o total de registros do próprio grupo de gênero como denominador.

### Limitações

A base conserva registros repetidos cuja exclusão não foi justificada.

Por isso, os resultados devem ser interpretados como distribuição de registros, sem pressupor que cada linha represente uma unidade física vendida.

Além disso, diferenças nas frequências das categorias não comprovam, isoladamente, preferências de consumo ou relações causais entre gênero e comportamento de compra.

In [20]:
# CP4.5 — Distribuição cruzada entre gênero e categoria de produto

distribuicao_genero_categoria = (
    df_funcao
    .groupby(["CL_GENERO", "PR_CAT"])
    .size()
    .reset_index(name="registros")
)

# Total de registros dentro de cada grupo de gênero
total_por_genero = (
    df_funcao
    .groupby("CL_GENERO")
    .size()
    .rename("total_genero")
)

# Acrescentar o total do gênero à tabela
distribuicao_genero_categoria = (
    distribuicao_genero_categoria
    .merge(
        total_por_genero,
        on="CL_GENERO"
    )
)

# Calcular percentuais mantendo a precisão original
distribuicao_genero_categoria["percentual_no_genero"] = (
    distribuicao_genero_categoria["registros"]
    / distribuicao_genero_categoria["total_genero"]
    * 100
)

# Arredondar somente para exibir
tabela_exibicao = distribuicao_genero_categoria.copy()

tabela_exibicao["percentual_no_genero"] = (
    tabela_exibicao["percentual_no_genero"]
    .round(2)
)

display(tabela_exibicao)


# =========================
# VALIDAÇÕES
# =========================

print("VALIDAÇÃO DO TOTAL GERAL")
print("Total da df_funcao:", len(df_funcao))

total_agrupamento = (
    distribuicao_genero_categoria["registros"].sum()
)

print("Total obtido no agrupamento:", total_agrupamento)

print(
    "Total geral confere:",
    total_agrupamento == len(df_funcao)
)

print("\nVALIDAÇÃO DOS TOTAIS POR GÊNERO")

validacao_genero = (
    distribuicao_genero_categoria
    .groupby("CL_GENERO")["registros"]
    .sum()
    .reset_index(name="total_calculado")
)

display(validacao_genero)

print("\nVALIDAÇÃO DOS PERCENTUAIS POR GÊNERO")

validacao_percentual = (
    distribuicao_genero_categoria
    .groupby("CL_GENERO")["percentual_no_genero"]
    .sum()
    .reset_index(name="soma_percentuais")
)

# Arredondamento apenas para exibição da validação
display(validacao_percentual.round(6))

   CL_GENERO         PR_CAT  registros  total_genero  percentual_no_genero
0          F     ACESSORIOS       7700        432576                  1.78
1          F      ALIMENTOS     226575        432576                 52.38
2          F        BEBIDAS      22345        432576                  5.17
3          F        HIGIENE      80991        432576                 18.72
4          F        LIMPEZA      76298        432576                 17.64
5          F  NÃO INFORMADA       1918        432576                  0.44
6          F            PET      16749        432576                  3.87
7          M     ACESSORIOS       6857        397424                  1.73
8          M      ALIMENTOS     208192        397424                 52.39
9          M        BEBIDAS      20954        397424                  5.27
10         M        HIGIENE      74583        397424                 18.77
11         M        LIMPEZA      69456        397424                 17.48
12         M  NÃO INFORMADA       1732        397424                  0.44
13         M            PET      15650        397424                  3.94

VALIDAÇÃO DO TOTAL GERAL
Total da df_funcao: 830000
Total obtido no agrupamento: 830000
Total geral confere: True

VALIDAÇÃO DOS TOTAIS POR GÊNERO

  CL_GENERO  total_calculado
0         F           432576
1         M           397424

VALIDAÇÃO DOS PERCENTUAIS POR GÊNERO

  CL_GENERO  soma_percentuais
0         F             100.0
1         M             100.0

### Interpretação dos resultados do CP4.5

**1. Distribuição das categorias**

A análise mostra que a categoria `ALIMENTOS` concentra o maior número de registros nos grupos de gênero analisados.

A distribuição relativa das categorias apresenta um padrão semelhante entre os grupos M e F.

**2. Comparação entre os grupos**

Embora existam diferenças nas contagens absolutas, a comparação percentual reduz o efeito das diferenças no volume total de registros de cada grupo.

Isso permite comparar a participação relativa das categorias, considerando o total de registros de cada grupo de gênero.

**3. Significado dos resultados**

Os valores obtidos representam ocorrências registradas na Base Varejo.

Essas contagens não devem ser interpretadas automaticamente como quantidade física de produtos adquiridos, valor gasto ou preferência dos consumidores.

**4. Qualidade dos dados**

Os registros completamente repetidos foram preservados porque não há evidência suficiente para classificá-los como erros.

Essa decisão pode influenciar as contagens observadas e deve ser considerada na interpretação dos resultados.

**5. Limitações da análise**

Uma mesma compra pode conter produtos de diferentes categorias.

Portanto, eventuais contagens de compras distintas por categoria não são necessariamente aditivas entre si.

Além disso, as distribuições observadas não permitem estabelecer relações causais entre gênero e comportamento de consumo.

## CP4.6 — Distribuição das categorias de produtos por segmento

### Pergunta de investigação

Como as categorias de produtos estão distribuídas entre os segmentos de clientes A, B e C?

### Objetivo

No CP4.5, investigamos a distribuição das categorias de produtos por gênero.

Agora, vamos aprofundar a análise cruzando as colunas `CL_SEG` e `PR_CAT`, para identificar como os registros das diferentes categorias estão distribuídos entre os segmentos existentes na base.

A investigação permitirá comparar a composição dos segmentos, considerando tanto as quantidades absolutas quanto as participações percentuais das categorias.

### Unidade de análise

A unidade utilizada será o **registro da Base Varejo**, contado em cada combinação entre segmento e categoria de produto.

Cada linha representa uma ocorrência documentada, não necessariamente uma unidade física vendida.

### Procedimento

Serão investigados:

- A quantidade de registros em cada categoria por segmento.
- O total de registros pertencentes a cada segmento.
- A participação percentual de cada categoria dentro do respectivo segmento.
- A consistência dos totais obtidos em relação à base tratada.

### Cuidados metodológicos

Os segmentos serão identificados apenas pelos códigos `A`, `B` e `C`, conforme aparecem na base original.

Não serão atribuídas classificações socioeconômicas ou características comerciais sem documentação que sustente essas interpretações.

Os registros duplicados anteriormente identificados permanecem preservados, pois não há evidência suficiente para considerá-los erros.

Portanto, os resultados representarão a distribuição dos registros, e não faturamento, quantidade física vendida ou preferência comprovada dos consumidores.

In [21]:
# CP4.6 — Distribuição das categorias por segmento

# Base: df_funcao (dados tratados na Sprint 3)

# 1. Contar registros por combinação de segmento e categoria

distribuicao_segmento_categoria = (
    df_funcao
    .groupby(["CL_SEG", "PR_CAT"])
    .size()
    .reset_index(name="QTD_REGISTROS")
)

print("ETAPA 1 — AGRUPAMENTO")
display(distribuicao_segmento_categoria)


# 2. Calcular o total de registros de cada segmento

totais_segmento = (
    df_funcao
    .groupby("CL_SEG")
    .size()
    .reset_index(name="TOTAL_SEGMENTO")
)

print("\nETAPA 2 — TOTAIS POR SEGMENTO")
display(totais_segmento)


# 3. Calcular percentuais dentro de cada segmento, sem arredondamento prévio

distribuicao_segmento_categoria = distribuicao_segmento_categoria.merge(
    totais_segmento,
    on="CL_SEG",
    how="left"
)

distribuicao_segmento_categoria["PERCENTUAL"] = (
    distribuicao_segmento_categoria["QTD_REGISTROS"]
    / distribuicao_segmento_categoria["TOTAL_SEGMENTO"]
    * 100
)


# 4. Organizar a tabela e arredondar somente para exibição

tabela_apresentacao = distribuicao_segmento_categoria.copy()

tabela_apresentacao["PERCENTUAL_EXIBICAO"] = (
    tabela_apresentacao["PERCENTUAL"].round(2)
)

tabela_apresentacao = tabela_apresentacao[
    [
        "CL_SEG",
        "PR_CAT",
        "QTD_REGISTROS",
        "TOTAL_SEGMENTO",
        "PERCENTUAL_EXIBICAO"
    ]
].sort_values(
    by=["CL_SEG", "PR_CAT"]
).reset_index(drop=True)

print("\nETAPA 4 — TABELA COMPARATIVA")
display(tabela_apresentacao)


# 5. Validar totais, segmentos, categorias e percentuais

print("\nETAPA 5 — VALIDAÇÕES")


# 5.1. Conferir o total agrupado de 830.000 registros

total_agrupado = distribuicao_segmento_categoria["QTD_REGISTROS"].sum()

print(
    "1. Total de registros dos agrupamentos:",
    total_agrupado,
    "| Esperado: 830000",
    "| OK:", total_agrupado == 830000
)


# 5.2. Conferir os segmentos A, B e C

segmentos_encontrados = set(
    distribuicao_segmento_categoria["CL_SEG"].unique()
)

segmentos_esperados = {"A", "B", "C"}

print(
    "2. Segmentos encontrados:",
    sorted(segmentos_encontrados),
    "| Esperados: A, B e C",
    "| OK:", segmentos_encontrados == segmentos_esperados
)


# 5.3. Conferir as sete categorias por segmento

categorias_por_segmento = (
    distribuicao_segmento_categoria
    .groupby("CL_SEG")["PR_CAT"]
    .nunique()
)

print("\n3. Quantidade de categorias por segmento:")
display(
    categorias_por_segmento
    .reset_index(name="QTD_CATEGORIAS")
)

validacao_sete_categorias = (
    categorias_por_segmento == 7
).all()

print(
    "Todos os segmentos possuem sete categorias:",
    validacao_sete_categorias
)


# 5.4. Conferir a soma de 100% dos percentuais por segmento

soma_percentuais = (
    distribuicao_segmento_categoria
    .groupby("CL_SEG")["PERCENTUAL"]
    .sum()
    .reset_index(name="SOMA_PERCENTUAL")
)

print("\n4. Soma percentual por segmento:")
display(soma_percentuais)

validacao_percentuais = (
    soma_percentuais["SOMA_PERCENTUAL"]
    .sub(100)
    .abs()
    .lt(1e-9)
    .all()
)

print(
    "Todos os segmentos somam aproximadamente 100%:",
    validacao_percentuais
)


# 5.5. Registrar o término das validações

print("\n5. Execução concluída sem erros.")

ETAPA 1 — AGRUPAMENTO

   CL_SEG         PR_CAT  QTD_REGISTROS
0       A     ACESSORIOS           1175
1       A      ALIMENTOS          35292
2       A        BEBIDAS           3601
3       A        HIGIENE          12844
4       A        LIMPEZA          11915
5       A  NÃO INFORMADA            289
6       A            PET           2620
7       B     ACESSORIOS           9234
8       B      ALIMENTOS         277781
9       B        BEBIDAS          27554
10      B        HIGIENE          99390
11      B        LIMPEZA          93016
12      B  NÃO INFORMADA           2330
13      B            PET          20858
14      C     ACESSORIOS           4148
15      C      ALIMENTOS         121694
16      C        BEBIDAS          12144
17      C        HIGIENE          43340
18      C        LIMPEZA          40823
19      C  NÃO INFORMADA           1031
20      C            PET           8921

ETAPA 2 — TOTAIS POR SEGMENTO

  CL_SEG  TOTAL_SEGMENTO
0      A           67736
1      B          530163
2      C          232101

ETAPA 4 — TABELA COMPARATIVA

   CL_SEG         PR_CAT  QTD_REGISTROS  TOTAL_SEGMENTO  PERCENTUAL_EXIBICAO
0       A     ACESSORIOS           1175           67736                 1.73
1       A      ALIMENTOS          35292           67736                52.10
2       A        BEBIDAS           3601           67736                 5.32
3       A        HIGIENE          12844           67736                18.96
4       A        LIMPEZA          11915           67736                17.59
5       A  NÃO INFORMADA            289           67736                 0.43
6       A            PET           2620           67736                 3.87
7       B     ACESSORIOS           9234          530163                 1.74
8       B      ALIMENTOS         277781          530163                52.40
9       B        BEBIDAS          27554          530163                 5.20
10      B        HIGIENE          99390          530163                18.75
11      B        LIMPEZA          93016          530163                17.54
12      B  NÃO INFORMADA           2330          530163                 0.44
13      B            PET          20858          530163                 3.93
14      C     ACESSORIOS           4148          232101                 1.79
15      C      ALIMENTOS         121694          232101                52.43
16      C        BEBIDAS          12144          232101                 5.23
17      C        HIGIENE          43340          232101                18.67
18      C        LIMPEZA          40823          232101                17.59
19      C  NÃO INFORMADA           1031          232101                 0.44
20      C            PET           8921          232101                 3.84

ETAPA 5 — VALIDAÇÕES
1. Total de registros dos agrupamentos: 830000 | Esperado: 830000 | OK: True
2. Segmentos encontrados: ['A', 'B', 'C'] | Esperados: A, B e C | OK: True

3. Quantidade de categorias por segmento:

  CL_SEG  QTD_CATEGORIAS
0      A               7
1      B               7
2      C               7

Todos os segmentos possuem sete categorias: True

4. Soma percentual por segmento:

  CL_SEG  SOMA_PERCENTUAL
0      A            100.0
1      B            100.0
2      C            100.0

Todos os segmentos somam aproximadamente 100%: True

5. Execução concluída sem erros.

### Interpretação dos resultados do CP4.6

**1. Distribuição das categorias**

A análise considera a distribuição das categorias de produtos dentro dos segmentos A, B e C.

Nos três segmentos, a categoria **ALIMENTOS** apresenta a maior participação. No segmento A, representa **52,10%** dos registros, com **35.292 ocorrências**. No segmento B, corresponde a **52,40%**, com **277.781 registros**. No segmento C, alcança **52,43%**, com **121.694 registros**.

Na sequência, aparecem as categorias **HIGIENE** e **LIMPEZA**, também com participações bastante semelhantes entre os três segmentos. HIGIENE representa **18,96%** no segmento A, **18,75%** no segmento B e **18,67%** no segmento C. LIMPEZA representa **17,59%** no segmento A, **17,54%** no segmento B e **17,59%** no segmento C.

As demais categorias apresentam participações menores. BEBIDAS corresponde a **5,32%**, **5,20%** e **5,23%** nos segmentos A, B e C, respectivamente. PET representa **3,87%**, **3,93%** e **3,84%**, enquanto ACESSORIOS corresponde a **1,73%**, **1,74%** e **1,79%**.

A categoria com menor participação em todos os segmentos é **NÃO INFORMADA**, com **0,43%** no segmento A e **0,44%** nos segmentos B e C. Em valores absolutos, foram identificados **289 registros** no segmento A, **2.330** no segmento B e **1.031** no segmento C nessa categoria.

**2. Comparação entre os segmentos**

A comparação entre os segmentos deve considerar tanto as contagens absolutas quanto a participação percentual de cada categoria.

Os percentuais permitem comparar a composição dos grupos, sem depender exclusivamente das diferenças no número total de registros.

Em termos absolutos, o segmento **B** apresenta o maior volume, com **530.163 registros**, seguido pelo segmento **C**, com **232.101**, e pelo segmento **A**, com **67.736 registros**. Apesar dessa diferença expressiva de tamanho, a composição percentual dos três segmentos é muito semelhante.

A categoria ALIMENTOS, por exemplo, varia apenas de **52,10% a 52,43%** entre os segmentos. HIGIENE varia de **18,67% a 18,96%**, enquanto LIMPEZA permanece praticamente estável, entre **17,54% e 17,59%**. O mesmo padrão ocorre em BEBIDAS, com valores entre **5,20% e 5,32%**, em PET, entre **3,84% e 3,93%**, e em ACESSORIOS, entre **1,73% e 1,79%**.

Esses resultados indicam que, embora os segmentos tenham quantidades absolutas de registros muito diferentes, **a distribuição relativa das categorias é bastante homogênea entre A, B e C**. Não foi observada, nesta análise descritiva, nenhuma categoria cuja participação percentual diferencie fortemente um segmento dos demais.

**3. Significado das métricas**

A contagem absoluta representa a quantidade de registros associados a cada combinação entre categoria de produto e segmento.

Já a participação percentual indica quanto determinada categoria representa dentro do total de registros do segmento correspondente.

Essas medidas descrevem a composição dos registros da base, não necessariamente a quantidade física de produtos vendidos ou o valor financeiro das compras.

Os resultados mostram, portanto, a frequência relativa com que cada categoria aparece nos registros de cada segmento, permitindo comparar grupos de tamanhos diferentes sem que o volume absoluto seja o único fator considerado.

**4. Qualidade dos dados**

A categoria `NÃO INFORMADA` permanece na análise para preservar os registros cuja classificação original não estava disponível.

Ela representa uma parcela pequena da base em todos os segmentos: **0,43% no segmento A e 0,44% nos segmentos B e C**. Apesar da baixa participação percentual, esses registros foram mantidos para evitar perda de informação e preservar a rastreabilidade da base original.

Os registros repetidos também foram mantidos, conforme as decisões justificadas na Sprint 2.

Essas características devem ser consideradas na interpretação das contagens e participações percentuais. As validações executadas também indicam consistência interna dos resultados: os agrupamentos totalizam **830.000 registros**, os segmentos encontrados são exatamente A, B e C, cada segmento apresenta **sete categorias**, e a soma dos percentuais de cada segmento corresponde a aproximadamente **100%**.

**5. Limitações da análise**

Os códigos `A`, `B` e `C` foram preservados conforme a fonte e não receberam interpretações adicionais sem confirmação documental.

A análise não permite calcular diretamente quantidade física vendida, faturamento ou preferências individuais.

As diferenças observadas representam associações descritivas entre categorias e segmentos, sem demonstrar, isoladamente, suas causas.

Além disso, como a composição percentual dos três segmentos é muito semelhante, os resultados do CP4.6 não sustentam, por si só, a conclusão de que determinado segmento possua comportamento de consumo significativamente diferente dos demais. Para investigar diferenças comportamentais ou comerciais, seriam necessárias outras variáveis e métricas da base.

## CP4.7 — Investigação dos produtos e de suas frequências

### Pergunta de investigação

Quais produtos apresentam maior frequência nos registros da Base Varejo, e como essa distribuição muda quando consideramos compras e clientes distintos?

### Objetivo

Nas investigações anteriores, foram comparadas categorias de produtos por gênero e segmento.

Agora, o objetivo é aprofundar a análise no nível dos produtos individuais, utilizando seus códigos e nomes.

A proposta é distinguir diferentes medidas de frequência e verificar como a unidade de análise influencia a interpretação.

### Unidade de análise

Serão consideradas três medidas:

- **Registros:** quantidade de linhas associadas a cada produto.
- **Compras distintas:** quantidade de códigos `CO_ID` diferentes nos quais determinado produto aparece.
- **Clientes distintos:** quantidade de códigos `CL_ID` diferentes associados ao produto.

Essas medidas não são equivalentes.

### Procedimento

A investigação deverá identificar os produtos por `PR_ID` e `PR_NOME`, calcular as três medidas e comparar os resultados.

Também será necessário considerar o impacto potencial dos registros repetidos e dos produtos sem identificação completa.

### Cuidados metodológicos

O número de registros não representa automaticamente quantidade física vendida.

O número de compras distintas não representa faturamento ou volume de unidades.

Os registros repetidos serão preservados conforme as decisões justificadas na Sprint 2.

O produto identificado pelo código `107`, cuja descrição permanece não informada, deverá receber atenção específica na interpretação da qualidade dos dados.

In [22]:
# CP4.7 — Investigação dos produtos e de suas frequências

# 1. Identificar os produtos e verificar a consistência entre código e nome

# Selecionar os campos necessários à investigação
produtos_base = df_funcao[
    ['PR_ID', 'PR_NOME', 'CO_ID', 'CL_ID']
].copy()

# Contar os nomes associados a cada código
consistencia_produtos = (
    produtos_base
    .groupby('PR_ID')['PR_NOME']
    .nunique(dropna=False)
    .reset_index(name='qtd_nomes_associados')
)

# Localizar códigos com mais de um nome
inconsistencias_produtos = consistencia_produtos[
    consistencia_produtos['qtd_nomes_associados'] > 1
]

print('ETAPA 1 — Identificação e consistência dos produtos')
print(
    f'Produtos distintos por PR_ID: '
    f'{produtos_base["PR_ID"].nunique(dropna=False)}'
)
print(
    f'Códigos associados a mais de um nome: '
    f'{len(inconsistencias_produtos)}'
)

if len(inconsistencias_produtos) > 0:
    display(inconsistencias_produtos)
else:
    print('Não foram encontrados códigos associados a mais de um nome.')

print()


# 2. Contar registros por produto

frequencia_registros = (
    produtos_base
    .groupby(['PR_ID', 'PR_NOME'], dropna=False)
    .size()
    .reset_index(name='registros')
    .sort_values('registros', ascending=False)
)

print('ETAPA 2 — Produtos com maior frequência por registros')
display(frequencia_registros.head(10))

print()


# 3. Contar compras distintas por produto

frequencia_compras = (
    produtos_base
    .groupby(['PR_ID', 'PR_NOME'], dropna=False)['CO_ID']
    .nunique()
    .reset_index(name='compras_distintas')
    .sort_values('compras_distintas', ascending=False)
)

print('ETAPA 3 — Produtos presentes em mais compras distintas')
display(frequencia_compras.head(10))

print()


# 4. Contar clientes distintos por produto

frequencia_clientes = (
    produtos_base
    .groupby(['PR_ID', 'PR_NOME'], dropna=False)['CL_ID']
    .nunique()
    .reset_index(name='clientes_distintos')
    .sort_values('clientes_distintos', ascending=False)
)

print('ETAPA 4 — Produtos associados a mais clientes distintos')
display(frequencia_clientes.head(10))

print()


# 5. Comparar as três medidas por produto

comparacao_produtos = (
    frequencia_registros
    .merge(
        frequencia_compras,
        on=['PR_ID', 'PR_NOME'],
        how='outer'
    )
    .merge(
        frequencia_clientes,
        on=['PR_ID', 'PR_NOME'],
        how='outer'
    )
)

# Calcular o ranking por registros
comparacao_produtos['rank_registros'] = (
    comparacao_produtos['registros']
    .rank(method='min', ascending=False)
    .astype('Int64')
)

# Calcular o ranking por compras distintas
comparacao_produtos['rank_compras'] = (
    comparacao_produtos['compras_distintas']
    .rank(method='min', ascending=False)
    .astype('Int64')
)

# Calcular o ranking por clientes distintos
comparacao_produtos['rank_clientes'] = (
    comparacao_produtos['clientes_distintos']
    .rank(method='min', ascending=False)
    .astype('Int64')
)

comparacao_produtos = comparacao_produtos.sort_values(
    ['rank_registros', 'rank_compras', 'rank_clientes']
)

print('ETAPA 5 — Comparação das três medidas')

display(
    comparacao_produtos[
        [
            'PR_ID',
            'PR_NOME',
            'registros',
            'compras_distintas',
            'clientes_distintos',
            'rank_registros',
            'rank_compras',
            'rank_clientes'
        ]
    ].head(15)
)

print()


# 6. Verificar qualidade dos dados e validar indicadores

# 6.1. Verificar repetições por produto, compra e cliente

duplicadas_produto_compra_cliente = produtos_base.duplicated(
    subset=['PR_ID', 'PR_NOME', 'CO_ID', 'CL_ID'],
    keep=False
)

qtd_linhas_repetidas = duplicadas_produto_compra_cliente.sum()

print('ETAPA 6 — Qualidade e validação')
print(
    'Linhas envolvidas em repetições de '
    'PR_ID + PR_NOME + CO_ID + CL_ID:',
    qtd_linhas_repetidas
)

print()


# 6.2. Comparar registros e compras distintas

registros_vs_compras = (
    produtos_base
    .groupby(['PR_ID', 'PR_NOME'], dropna=False)
    .agg(
        registros=('CO_ID', 'size'),
        compras_distintas=('CO_ID', 'nunique')
    )
    .reset_index()
)

registros_vs_compras['diferenca'] = (
    registros_vs_compras['registros']
    - registros_vs_compras['compras_distintas']
)

registros_vs_compras['registros_por_compra'] = (
    registros_vs_compras['registros']
    / registros_vs_compras['compras_distintas']
)

print('Produtos com maior diferença entre registros e compras distintas')

display(
    registros_vs_compras
    .sort_values('diferenca', ascending=False)
    .head(10)
)

print()


# 6.3. Conferir o produto de código 107

produto_107 = produtos_base[
    produtos_base['PR_ID'].astype(str).str.strip() == '107'
]

print('Produto PR_ID = 107')
print(f'Quantidade de registros: {len(produto_107)}')

if len(produto_107) > 0:
    print(
        'Compras distintas:',
        produto_107['CO_ID'].nunique()
    )

    print(
        'Clientes distintos:',
        produto_107['CL_ID'].nunique()
    )

    print(
        'Descrições encontradas:',
        produto_107['PR_NOME'].drop_duplicates().tolist()
    )

    display(produto_107.head(20))
else:
    print('O produto 107 não foi encontrado na base tratada.')

print()


# 6.4. Verificar nomes ausentes, vazios ou marcados como NÃO INFORMADO

produtos_sem_nome = produtos_base[
    produtos_base['PR_NOME'].isna()
    | produtos_base['PR_NOME'].astype(str).str.strip().isin(
        ['', 'nan', 'None', 'NÃO INFORMADO']
    )
]

print(
    'Registros com PR_NOME ausente, vazio ou NÃO INFORMADO:',
    len(produtos_sem_nome)
)

if len(produtos_sem_nome) > 0:
    display(
        produtos_sem_nome[
            ['PR_ID', 'PR_NOME']
        ]
        .drop_duplicates()
        .sort_values('PR_ID')
    )

print()


# 6.5. Resumir os líderes de cada indicador

top_registros = frequencia_registros.iloc[0]
top_compras = frequencia_compras.iloc[0]
top_clientes = frequencia_clientes.iloc[0]

print('RESUMO DA INVESTIGAÇÃO')

print(
    f'Maior número de registros: '
    f'{top_registros["PR_ID"]} - {top_registros["PR_NOME"]} '
    f'({top_registros["registros"]} registros)'
)

print(
    f'Maior número de compras distintas: '
    f'{top_compras["PR_ID"]} - {top_compras["PR_NOME"]} '
    f'({top_compras["compras_distintas"]} compras)'
)

print(
    f'Maior número de clientes distintos: '
    f'{top_clientes["PR_ID"]} - {top_clientes["PR_NOME"]} '
    f'({top_clientes["clientes_distintos"]} clientes)'
)

ETAPA 1 — Identificação e consistência dos produtos
Produtos distintos por PR_ID: 229
Códigos associados a mais de um nome: 0
Não foram encontrados códigos associados a mais de um nome.

ETAPA 2 — Produtos com maior frequência por registros

     PR_ID             PR_NOME  registros
92      93      AGUA SANITARIA       3773
97      98     DESENGORDURANTE       3760
36      37               LEITE       3757
60      61            SARDINHA       3746
128    129            SARDINHA       3744
189    190                 GEL       3736
173    174  LIMPADOR PERFUMADO       3730
19      20              CEBOLA       3730
50      51    PAPINHA INFANTIL       3726
102    103   LIMPADOR MULTIUSO       3723

ETAPA 3 — Produtos presentes em mais compras distintas

     PR_ID             PR_NOME  compras_distintas
50      51    PAPINHA INFANTIL               3322
22      23           COGUMELOS               3315
97      98     DESENGORDURANTE               3308
92      93      AGUA SANITARIA               3306
128    129            SARDINHA               3306
60      61            SARDINHA               3304
220    221              BANANA               3290
168    169               MAMAO               3289
173    174  LIMPADOR PERFUMADO               3288
19      20              CEBOLA               3287

ETAPA 4 — Produtos associados a mais clientes distintos

     PR_ID               PR_NOME  clientes_distintos
154    155                  PATE                 975
98      99          DESINFETANTE                 974
14      15           BATATA DOCE                 974
227    228             AMACIANTE                 974
95      96                 BALDE                 973
224    225                  ATUM                 972
40      41              MACARRAO                 971
59      60  SALGADINHOS DE MILHO                 970
7        8                 ARROZ                 970
209    210               CHUPETA                 969

ETAPA 5 — Comparação das três medidas

,PR_ID,PR_NOME,registros,compras_distintas,clientes_distintos,rank_registros,rank_compras,rank_clientes
92,93,AGUA SANITARIA,3773,3306,956,1,4,154
97,98,DESENGORDURANTE,3760,3308,960,2,3,83
36,37,LEITE,3757,3258,964,3,32,44
60,61,SARDINHA,3746,3304,962,4,6,56
128,129,SARDINHA,3744,3306,960,5,4,83
189,190,GEL,3736,3273,960,6,16,83
173,174,LIMPADOR PERFUMADO,3730,3288,965,7,9,30
19,20,CEBOLA,3730,3287,962,7,10,56
50,51,PAPINHA INFANTIL,3726,3322,969,9,1,10
102,103,LIMPADOR MULTIUSO,3723,3268,958,10,21,124
220,221,BANANA,3718,3290,961,11,7,72
22,23,COGUMELOS,3715,3315,966,12,2,24
168,169,MAMAO,3712,3289,956,13,8,154
195,196,ESCOVA DE DENTE,3712,3273,956,13,16,154
222,223,AZEITONA,3710,3285,957,15,11,139

ETAPA 6 — Qualidade e validação
Linhas envolvidas em repetições de PR_ID + PR_NOME + CO_ID + CL_ID: 184330

Produtos com maior diferença entre registros e compras distintas

,PR_ID,PR_NOME,registros,compras_distintas,diferenca,registros_por_compra
36,37,LEITE,3757,3258,499,1.153161
145,146,RACAO UMIDA PARA CAES,3667,3198,469,1.146654
92,93,AGUA SANITARIA,3773,3306,467,1.141258
202,203,DANETTE,3668,3202,466,1.145534
189,190,GEL,3736,3273,463,1.141460
15,16,BIFE DE COXAO MOLE,3692,3232,460,1.142327
223,224,AZEITE,3651,3193,458,1.143439
81,82,LENCO UMEDECIDO,3647,3191,456,1.142902
203,204,CREME,3691,3236,455,1.140606
102,103,LIMPADOR MULTIUSO,3723,3268,455,1.139229

Produto PR_ID = 107
Quantidade de registros: 3650
Compras distintas: 3228
Clientes distintos: 956
Descrições encontradas: ['NÃO INFORMADO']

      PR_ID        PR_NOME  CO_ID  CL_ID
82      107  NÃO INFORMADO   1078    290
223     107  NÃO INFORMADO   1103    957
640     107  NÃO INFORMADO   1482    453
857     107  NÃO INFORMADO   1683    438
917     107  NÃO INFORMADO   1793    608
1185    107  NÃO INFORMADO   2151    493
1273    107  NÃO INFORMADO   2224    497
1303    107  NÃO INFORMADO   2311    164
1325    107  NÃO INFORMADO   2311    164
1385    107  NÃO INFORMADO   2327    689
1542    107  NÃO INFORMADO   2522    340
1594    107  NÃO INFORMADO   2668    574
1831    107  NÃO INFORMADO   3076    458
2061    107  NÃO INFORMADO   3395    798
2103    107  NÃO INFORMADO   3444    709
2435    107  NÃO INFORMADO   3763    433
2589    107  NÃO INFORMADO   4009    922
2768    107  NÃO INFORMADO   4153    193
3002    107  NÃO INFORMADO   4578    523
3010    107  NÃO INFORMADO   4578    523

Registros com PR_NOME ausente, vazio ou NÃO INFORMADO: 3650

    PR_ID        PR_NOME
82    107  NÃO INFORMADO

RESUMO DA INVESTIGAÇÃO
Maior número de registros: 93 - AGUA SANITARIA (3773 registros)
Maior número de compras distintas: 51 - PAPINHA INFANTIL (3322 compras)
Maior número de clientes distintos: 155 - PATE (975 clientes)

### Interpretação dos resultados do CP4.7

**1. Frequência dos produtos**

A contagem de registros mostra que os produtos com maior número de ocorrências na base tratada foram:

- **PR_ID 93 — AGUA SANITARIA:** 3.773 registros;
- **PR_ID 98 — DESENGORDURANTE:** 3.760 registros;
- **PR_ID 37 — LEITE:** 3.757 registros;
- **PR_ID 61 — SARDINHA:** 3.746 registros;
- **PR_ID 129 — SARDINHA:** 3.744 registros.

O produto **AGUA SANITARIA, PR_ID 93**, apresentou a maior frequência por registros, com **3.773 ocorrências**.

A verificação inicial identificou **229 produtos distintos por PR_ID** e não encontrou códigos associados a mais de um nome. Assim, dentro da base tratada, não foram observadas inconsistências do tipo **um mesmo PR_ID associado a diferentes valores de PR_NOME**.

---

**2. Compras e clientes distintos**

A ordenação dos produtos muda conforme a unidade considerada.

Por **compras distintas**, os produtos com maior presença foram:

- **PR_ID 51 — PAPINHA INFANTIL:** 3.322 compras;
- **PR_ID 23 — COGUMELOS:** 3.315 compras;
- **PR_ID 98 — DESENGORDURANTE:** 3.308 compras;
- **PR_ID 93 — AGUA SANITARIA:** 3.306 compras;
- **PR_ID 129 — SARDINHA:** 3.306 compras.

Nesse critério, **PAPINHA INFANTIL** passa para a primeira posição, embora ocupe a 9ª posição no ranking por quantidade de registros.

Por **clientes distintos**, os líderes são diferentes:

- **PR_ID 155 — PATE:** 975 clientes;
- **PR_ID 99 — DESINFETANTE:** 974 clientes;
- **PR_ID 15 — BATATA DOCE:** 974 clientes;
- **PR_ID 228 — AMACIANTE:** 974 clientes;
- **PR_ID 96 — BALDE:** 973 clientes.

Portanto, a ordenação muda de forma significativa entre as três métricas. Um produto com muitas ocorrências não é necessariamente aquele presente no maior número de compras nem aquele associado à maior quantidade de clientes.

Por exemplo, **AGUA SANITARIA** ocupa a 1ª posição em registros e a 4ª em compras distintas, mas apenas a **154ª posição em clientes distintos**. Já **PAPINHA INFANTIL** ocupa a 9ª posição em registros, a 1ª em compras distintas e a 10ª em clientes distintos.

Essas diferenças demonstram que cada indicador mede uma característica específica da presença dos produtos na base.

---

**3. Diferença entre as métricas**

A contagem de registros considera todas as ocorrências de determinado produto na base.

A contagem de compras distintas identifica quantas compras diferentes incluem esse produto.

A contagem de clientes distintos identifica quantos clientes diferentes aparecem associados ao produto.

Portanto, os três indicadores representam aspectos diferentes da distribuição dos produtos.

A comparação entre registros e compras distintas mostra ainda que determinados produtos aparecem mais de uma vez dentro de uma mesma compra.

O maior afastamento foi observado para **PR_ID 37 — LEITE**, que apresenta:

- 3.757 registros;
- 3.258 compras distintas;
- diferença de 499 ocorrências;
- aproximadamente **1,153 registro por compra distinta**.

Outros produtos também apresentam diferenças relevantes, como **RACAO UMIDA PARA CAES**, **AGUA SANITARIA**, **DANETTE** e **GEL**.

Esses resultados reforçam que a contagem simples de registros não pode ser interpretada como equivalente à quantidade de compras.

---

**4. Qualidade dos dados**

A verificação identificou **184.330 linhas envolvidas em repetições da combinação PR_ID + PR_NOME + CO_ID + CL_ID**.

Esse resultado deve ser interpretado com cautela. O valor representa o número de **linhas que participam de combinações repetidas**, e não necessariamente 184.330 registros excedentes que poderiam ser eliminados.

A repetição pode decorrer da própria estrutura ou granularidade da base. Portanto, não há evidência suficiente, apenas com essa verificação, para considerar essas linhas erros ou removê-las.

A investigação específica do **PR_ID 107** identificou:

- **3.650 registros**;
- **3.228 compras distintas**;
- **956 clientes distintos**;
- descrição encontrada: **NÃO INFORMADO**.

Assim, o produto 107 está presente de forma relevante na base, mas sua identificação nominal não está disponível.

Os mesmos **3.650 registros** correspondem ao total identificado pela verificação de nomes ausentes, vazios ou marcados como **NÃO INFORMADO**. Não foram observados outros produtos nessa condição no resultado apresentado.

Como não existe informação adicional suficiente para determinar qual produto corresponde ao PR_ID 107, não é adequado atribuir um nome por inferência, substituir o valor ou eliminar esses registros. O tratamento correto é preservar o código e registrar a ausência da descrição como uma limitação de qualidade dos dados.

---

**5. Limitações da análise**

A base não contém campos que permitam identificar diretamente quantidade física vendida ou valor financeiro das operações.

Consequentemente, os rankings obtidos não representam necessariamente os produtos com maior volume físico de vendas ou maior faturamento.

Também não é possível concluir, apenas pelas repetições identificadas, que existam duplicidades indevidas. Para isso, seria necessário conhecer com maior precisão a granularidade esperada de cada registro da base e verificar se existem outros atributos capazes de distinguir itens aparentemente repetidos.

Da mesma forma, o produto de código **107** não pode ser identificado nominalmente com os dados atualmente disponíveis.

A interpretação deve, portanto, respeitar as unidades utilizadas em cada cálculo:

- **registros** representam ocorrências na base;
- **compras distintas** representam CO_ID únicos;
- **clientes distintos** representam CL_ID únicos.

Essas métricas são complementares e não devem ser tratadas como equivalentes a quantidade vendida, faturamento ou participação financeira dos produtos.

## CP4.8 — Análise temporal das compras

### Pergunta de investigação

Como as compras da Base Varejo estão distribuídas ao longo do período registrado na coluna `DATA`?

### Objetivo

Nas análises anteriores, investigamos categorias, gêneros, segmentos e produtos.

Neste checkpoint, vamos acrescentar a dimensão temporal para compreender como as operações de compra estão distribuídas entre diferentes meses.

### Unidade de análise

A principal unidade será a **compra distinta**, identificada por `CO_ID`.

Como uma mesma compra pode aparecer em várias linhas, a contagem de registros não será utilizada como equivalente ao número de compras.

### Procedimento

A investigação compreenderá:

- Validação do formato das datas;
- Identificação do período coberto pela base;
- Agrupamento das compras por mês;
- Contagem de compras distintas em cada período;
- Comparação dos resultados encontrados;
- Conferência da consistência das datas e dos indicadores.

### Cuidados metodológicos

A coluna `DATA` deverá ser convertida para um formato de data adequado, preservando os dados originais.

O período observado deverá ser considerado antes de realizar comparações entre meses.

Diferenças temporais serão interpretadas de maneira descritiva, sem afirmar sazonalidade ou relações causais que não estejam comprovadas pelos dados.

In [23]:
# CP4.8 — Análise temporal das compras
# Unidade de análise: compra distinta (CO_ID)

import pandas as pd

# Trabalhar em uma cópia para preservar a base tratada
df_temporal = df_funcao.copy()

# 1. Preservar a coluna original
df_temporal["DATA_ORIGINAL"] = df_temporal["DATA"].copy()

# 2. Inspecionar o formato real antes da conversão
print("Amostra dos valores originais de DATA:")
print(df_temporal["DATA"].head(10))

print("\nTipo original da coluna DATA:")
print(df_temporal["DATA"].dtype)

print("\nValores ausentes em DATA:")
print(df_temporal["DATA"].isna().sum())

# 3. Converter DATA para datetime
# Formato dia/mês/ano identificado na base
df_temporal["DATA_DT"] = pd.to_datetime(
    df_temporal["DATA"],
    format="%d/%m/%Y",
    errors="coerce"
)

# 4. Conferir se houve falhas na conversão
falhas_conversao = df_temporal[
    df_temporal["DATA"].notna()
    & df_temporal["DATA_DT"].isna()
]

print("\nFalhas de conversão:")
print(len(falhas_conversao))

if len(falhas_conversao) > 0:
    print("\nExemplos de valores que não puderam ser convertidos:")
    print(
        falhas_conversao["DATA"]
        .drop_duplicates()
        .head(20)
    )

# 5. Identificar o período coberto pela base
data_inicial = df_temporal["DATA_DT"].min()
data_final = df_temporal["DATA_DT"].max()

print("\nPeríodo coberto pela base:")
print("Data inicial:", data_inicial)
print("Data final:", data_final)

# 6. Criar período mensal
df_temporal["MES"] = (
    df_temporal["DATA_DT"].dt.to_period("M")
)

# 7. Contar compras distintas por mês
compras_por_mes = (
    df_temporal
    .dropna(subset=["DATA_DT", "CO_ID"])
    .groupby("MES")["CO_ID"]
    .nunique()
    .reset_index(name="COMPRAS_DISTINTAS")
    .sort_values("MES")
)

# 8. Converter o período em texto para visualização
compras_por_mes["MES"] = (
    compras_por_mes["MES"].astype(str)
)

print("\nCompras distintas por mês:")
display(compras_por_mes)

# 9. Validação das compras
total_compras_periodo = (
    df_temporal.loc[
        df_temporal["DATA_DT"].notna(),
        "CO_ID"
    ].nunique()
)

total_soma_meses = (
    compras_por_mes["COMPRAS_DISTINTAS"].sum()
)

print("\nValidação das compras:")
print(
    "Compras distintas no período completo:",
    total_compras_periodo
)
print(
    "Soma das compras distintas mensais:",
    total_soma_meses
)

print(
    "Totais coincidem:",
    total_compras_periodo == total_soma_meses
)

# 10. Conferir a preservação da base tratada
print("\nValidação da base tratada:")
print(
    "Dimensões originais de df_funcao:",
    df_funcao.shape
)
print(
    "Dimensões da cópia temporal:",
    df_temporal.shape
)
print(
    "Total de registros preservado:",
    len(df_temporal) == len(df_funcao)
)

Amostra dos valores originais de DATA:
0    01/02/2019
1    01/02/2019
2    01/02/2019
3    01/02/2019
4    01/02/2019
5    01/02/2019
6    01/02/2019
7    01/02/2019
8    01/02/2019
9    01/02/2019
Name: DATA, dtype: object

Tipo original da coluna DATA:
object

Valores ausentes em DATA:
0

Falhas de conversão:
0

Período coberto pela base:
Data inicial: 2019-01-04 00:00:00
Data final: 2022-12-08 00:00:00

Compras distintas por mês:

        MES  COMPRAS_DISTINTAS
0   2019-01                171
1   2019-02                402
2   2019-03                257
3   2019-04                410
4   2019-05                711
5   2019-06                493
6   2019-07                274
7   2019-08                420
8   2019-09                436
9   2019-10                242
10  2019-11                151
11  2019-12                516
12  2020-01                506
13  2020-02                434
14  2020-03                439
15  2020-04                387
16  2020-05                366
17  2020-06                264
18  2020-07                215
19  2020-08                384
20  2020-09                471
21  2020-10                633
22  2020-11                384
23  2020-12                311
24  2021-01                616
25  2021-02                433
26  2021-03                382
27  2021-04                363
28  2021-05                333
29  2021-06                445
30  2021-07                599
31  2021-08                386
32  2021-09                594
33  2021-10                711
34  2021-11                231
35  2021-12                412
36  2022-01                566
37  2022-02                430
38  2022-03                364
39  2022-04                318
40  2022-05                429
41  2022-06                301
42  2022-07                446
43  2022-08                273
44  2022-09                 35
45  2022-10                 59
46  2022-11                155
47  2022-12                313

Validação das compras:
Compras distintas no período completo: 18471
Soma das compras distintas mensais: 18471
Totais coincidem: True

Validação da base tratada:
Dimensões originais de df_funcao: (830000, 10)
Dimensões da cópia temporal: (830000, 13)
Total de registros preservado: True

### Interpretação dos resultados do CP4.8

**1. Período analisado e consistência das datas**

A análise temporal identificou **18.471 compras distintas**, no período compreendido entre **4 de janeiro de 2019 e 8 de dezembro de 2022**.

A conversão da coluna `DATA` foi realizada sem perdas ou falhas, utilizando o formato de dia, mês e ano identificado na base.

A soma das compras distintas apuradas mensalmente coincide com o total de **18.471 compras distintas** do período analisado, demonstrando consistência entre os agrupamentos mensais e a contagem geral.

**2. Evolução anual das compras**

Em termos anuais, os resultados obtidos foram:

- **2019:** 4.483 compras distintas;
- **2020:** 4.794 compras distintas;
- **2021:** 5.505 compras distintas;
- **2022:** 3.689 compras distintas.

Entre 2019 e 2020, foi observado crescimento aproximado de **6,9%**.

Entre 2020 e 2021, o crescimento foi de aproximadamente **14,8%**.

Assim, **2021 apresentou o maior volume anual de compras distintas** da série analisada.

Em 2022, o total foi de **3.689 compras**, representando uma redução aproximada de **33%** em relação a 2021.

**3. Análise da mudança observada em 2022**

A redução registrada em 2022 não deve ser interpretada imediatamente como uma queda estrutural das compras.

Entre janeiro e agosto de 2022, foram identificadas **3.127 compras distintas**, volume próximo ao observado nos mesmos meses de anos anteriores.

A principal mudança aparece a partir de setembro:

- **Setembro de 2022:** 35 compras;
- **Outubro de 2022:** 59 compras;
- **Novembro de 2022:** 155 compras.

Esses valores representam uma alteração relevante na distribuição temporal observada.

Entretanto, os resultados não permitem afirmar, isoladamente, que essa diferença corresponde a uma mudança real no comportamento dos consumidores.

**4. Qualidade dos dados e validações**

A investigação confirmou que:

- Não foram encontrados valores ausentes na coluna `DATA`.
- Não foram identificadas falhas na conversão para o formato de data.
- O agrupamento mensal preservou a consistência das **18.471 compras distintas**.
- A base tratada original foi preservada durante o procedimento.

A análise temporal foi realizada sobre uma cópia da base, evitando a inclusão de colunas auxiliares no DataFrame utilizado para a exportação dos dados tratados.

**5. Limitações da análise**

Os baixos volumes observados no final de 2022 exigem investigação complementar.

É necessário verificar se estão relacionados à cobertura da base, filtros, alterações no processo de registro, mudanças de sistema ou ausência parcial de dados.

O período analisado também não contempla necessariamente meses completos em suas extremidades, pois começa em **4 de janeiro de 2019** e termina em **8 de dezembro de 2022**.

Portanto, comparações entre períodos devem considerar possíveis diferenças de cobertura.

De modo geral, os resultados mostram crescimento das compras distintas entre 2019 e 2021, seguido de uma ruptura atípica na distribuição temporal do último quadrimestre de 2022.

Esses resultados descrevem os registros disponíveis, sem demonstrar, isoladamente, causas comerciais ou comportamentais para as variações observadas.


# Fechamento da Sprint 4 — Análise dos dados

## 1. Análises realizadas

Nesta Sprint, foram aplicados filtros, agrupamentos, estatísticas básicas e investigações complementares sobre a Base Varejo tratada.

As análises foram organizadas em oito checkpoints, permitindo examinar os dados sob diferentes perspectivas: categorias, clientes, compras, gêneros, segmentos, produtos e períodos.

### CP4.1 — Aplicação de filtro

O filtro aplicado à categoria `BEBIDAS` identificou **43.299 registros**.

Esse resultado representa a quantidade de linhas da base associadas à categoria, não necessariamente o número de compras distintas ou de unidades comercializadas.

### CP4.2 — Agrupamentos

No agrupamento por categoria, `ALIMENTOS` apresentou a maior quantidade de registros, com **434.767 linhas**.

Na contagem de compras distintas por segmento, o segmento `B` apresentou o maior resultado, com **11.843 identificadores de compra diferentes**.

Esses procedimentos demonstraram a diferença entre utilizar `.size()` para contar registros e `.nunique()` para identificar valores distintos.

### CP4.3 — Estatísticas básicas

Foram analisadas **18.471 compras**, considerando a quantidade de códigos de produtos distintos (`PR_ID`) associados a cada compra (`CO_ID`).

Os resultados foram:

- **Contagem válida:** 18.471 compras;
- **Média:** 39,71 tipos de produtos distintos por compra;
- **Mínimo:** 1 tipo de produto por compra;
- **Máximo:** 81 tipos distintos em uma compra.

A medida representa a diversidade de códigos de produtos associados às compras, e não a quantidade física de produtos vendidos.

Ela foi construída a partir dos identificadores disponíveis, não correspondendo a uma coluna numérica original da base.

### CP4.4 — Perfil dos clientes por gênero

A análise comparou clientes distintos, compras distintas e registros nos grupos identificados por `F` e `M`.

O grupo `F` apresentou **519 clientes distintos, 9.615 compras distintas e 432.576 registros**.

O grupo `M` apresentou **481 clientes distintos, 8.856 compras distintas e 397.424 registros**.

A interpretação identificou uma distribuição relativamente equilibrada entre os grupos, com participação ligeiramente maior de `F` nos três indicadores.

As contagens foram interpretadas de acordo com suas unidades, sem atribuir diferenças de consumo ou comportamento apenas com base nos totais.

### CP4.5 — Categorias de produtos por gênero

O cruzamento entre `CL_GENERO` e `PR_CAT` permitiu comparar a composição das categorias dentro de cada grupo.

A categoria `ALIMENTOS` apresentou a maior participação nos dois grupos:

- **F:** 52,38% dos registros;
- **M:** 52,39% dos registros.

A distribuição relativa das categorias apresentou um padrão semelhante entre os grupos analisados.

Os resultados representam ocorrências na base e não permitem concluir, isoladamente, que existam preferências de consumo associadas ao gênero.

### CP4.6 — Categorias de produtos por segmento

Foram analisadas as sete categorias de produtos nos segmentos `A`, `B` e `C`.

A distribuição total de registros foi:

- **Segmento A:** 67.736 registros;
- **Segmento B:** 530.163 registros;
- **Segmento C:** 232.101 registros.

Apesar das diferenças nas quantidades absolutas, a composição percentual das categorias apresentou grande semelhança entre os segmentos.

Na categoria `ALIMENTOS`, as participações foram:

- **Segmento A:** 52,10%;
- **Segmento B:** 52,40%;
- **Segmento C:** 52,43%.

Os códigos dos segmentos foram preservados conforme a fonte, sem atribuição de significados econômicos não documentados.

### CP4.7 — Investigação dos produtos

A investigação identificou **229 códigos de produtos distintos** e comparou a frequência dos produtos por registros, compras distintas e clientes distintos.

Os líderes foram:

- **Registros:** `PR_ID 93 — AGUA SANITARIA`, com 3.773 ocorrências;
- **Compras distintas:** `PR_ID 51 — PAPINHA INFANTIL`, presente em 3.322 compras;
- **Clientes distintos:** `PR_ID 155 — PATE`, associado a 975 clientes.

Os resultados demonstraram que o produto com mais registros não é necessariamente aquele presente no maior número de compras ou associado ao maior número de clientes.

A investigação também identificou **184.330 linhas envolvidas em combinações repetidas de produto, compra e cliente**. Esse número representa linhas pertencentes a grupos repetidos, e não necessariamente registros excedentes que deveriam ser excluídos.

O produto de código `107` apresentou **3.650 registros** e permaneceu identificado como `NÃO INFORMADO`, respeitando a ausência de sua descrição original.

### CP4.8 — Análise temporal das compras

A investigação temporal examinou **18.471 compras distintas**, registradas entre **4 de janeiro de 2019 e 8 de dezembro de 2022**.

A distribuição anual foi:

- **2019:** 4.483 compras;
- **2020:** 4.794 compras;
- **2021:** 5.505 compras;
- **2022:** 3.689 compras.

Os resultados mostraram crescimento entre 2019 e 2021, seguido de redução no total registrado em 2022.

Foi identificada uma mudança acentuada a partir de setembro de 2022, cuja causa não pode ser determinada apenas com os dados disponíveis.

A análise temporal foi realizada sobre uma cópia da base tratada, preservando a estrutura original do DataFrame utilizado na exportação.

## 2. Aprendizados e decisões metodológicas

As investigações demonstraram a importância de definir corretamente a unidade de análise antes de interpretar os resultados.

As contagens de registros, compras distintas e clientes distintos representam medidas diferentes e não devem ser utilizadas como equivalentes.

A comparação por percentuais também permitiu examinar a composição de grupos com tamanhos diferentes, especialmente nas análises por gênero e segmento.

Os registros repetidos foram preservados porque não havia evidência suficiente para classificá-los como duplicidades indevidas.

Os valores não informados também foram mantidos e identificados, evitando atribuir informações não comprovadas aos produtos.

Na análise temporal, as colunas auxiliares foram criadas em uma cópia da base, preservando o DataFrame tratado.

## 3. Limitações da análise

A Base Varejo não possui campos de quantidade física vendida, preço, valor de venda, custo ou faturamento.

Portanto, as análises não permitem calcular diretamente unidades comercializadas, receita, ticket médio, lucro ou margem.

Também não é possível determinar as causas das diferenças entre grupos ou períodos apenas pelas contagens e proporções apresentadas.

Os códigos de segmentos e os produtos sem identificação completa não receberam interpretações adicionais sem evidência documental.

A análise temporal exige cautela quanto à cobertura do período, especialmente diante dos baixos volumes registrados no final de 2022.

No CP4.3, a estatística foi calculada sobre uma medida quantitativa derivada da contagem de códigos de produtos distintos por compra. Essa escolha está documentada, mas sua aderência à exigência de uma coluna numérica originalmente disponível na base depende da avaliação do critério institucional.

## 4. Conclusão da Sprint 4

Os oito checkpoints produziram resultados descritivos sobre categorias, clientes, compras, gêneros, segmentos, produtos e distribuição temporal.

As análises utilizaram os dados tratados e apresentaram contagens, agrupamentos, percentuais e estatísticas acompanhados de suas respectivas unidades e limitações metodológicas.

Os resultados demonstraram a importância de distinguir quantidade de registros, compras distintas e clientes distintos, preservando as informações disponíveis e evitando interpretações não sustentadas pelos dados.

A Sprint 4 reúne, assim, as análises desenvolvidas e interpretadas no notebook, servindo de base para a comunicação dos resultados e para a revisão dos arquivos de entrega nas etapas seguintes.

# Sprint 5 — Exportação e comunicação

## Objetivo

Salvar a versão tratada da Base Varejo e organizar os resultados da análise para que possam ser compreendidos e reproduzidos por outras pessoas.

## CP5.1 — Exportação da base tratada

O arquivo de saída deverá se chamar `varejo_limpo.csv`, sem incluir o índice do DataFrame.

A exportação deverá utilizar a versão tratada dos dados e preservar os registros que não tiveram exclusão justificada.

Após gerar o arquivo, será necessário verificar sua existência, conferir as dimensões e demonstrar que o processo pode ser reproduzido a partir da base original.

## CP5.2 — Comunicação dos resultados

Serão elaboradas de três a seis conclusões sustentadas por resultados numéricos, acompanhadas de uma recomendação e de uma limitação da análise.

## CP5.3 — Documentação

O `README.md` deverá explicar o objetivo do projeto, a origem dos dados, as colunas utilizadas, as decisões de limpeza, as instruções para execução e as principais conclusões.

Também deverá esclarecer como ocorreram as etapas de leitura, transformação e gravação dos dados.

In [24]:
# CP5.1 — Exportação e validação da Base Varejo

import os
import pandas as pd

# 1. Definir o arquivo de saída
arquivo_saida = "varejo_limpo.csv"

# 2. Exportar a base tratada, sem índice
df_funcao.to_csv(
    arquivo_saida,
    index=False,
    encoding="utf-8"
)

# 3. Conferir a existência e o tamanho do arquivo
arquivo_existe = os.path.isfile(arquivo_saida)

print("CP5.1 — EXPORTAÇÃO DA BASE TRATADA")
print("Arquivo:", arquivo_saida)
print("Arquivo existe:", arquivo_existe)

if not arquivo_existe:
    raise FileNotFoundError(
        f"Não foi possível localizar {arquivo_saida}"
    )

tamanho_bytes = os.path.getsize(arquivo_saida)

print("Tamanho do arquivo (bytes):", tamanho_bytes)
print("Caminho do arquivo:", os.path.abspath(arquivo_saida))

# 4. Ler novamente o CSV exportado
varejo_validacao = pd.read_csv(
    arquivo_saida,
    encoding="utf-8"
)

# 5. Conferir as dimensões
print("\nDIMENSÕES")
print("Base original:", df_bruto.shape)
print("Base tratada:", df_funcao.shape)
print("CSV exportado:", varejo_validacao.shape)

# 6. Verificar estrutura e conteúdo
validacoes = {
    "Arquivo não vazio":
        tamanho_bytes > 0,

    "Registros preservados":
        len(df_funcao) == len(df_bruto),

    "Dimensões do CSV correspondem":
        varejo_validacao.shape == df_funcao.shape,

    "Nomes e ordem das colunas correspondem":
        list(varejo_validacao.columns) == list(df_funcao.columns),

    "Sem colunas extras de índice":
        not any(
            coluna.startswith("Unnamed:")
            for coluna in varejo_validacao.columns
        ),

    "Conteúdo e ordem das linhas correspondem":
        df_funcao.reset_index(drop=True).equals(
            varejo_validacao.reset_index(drop=True)
        )
}

print("\nVALIDAÇÕES")
for descricao, resultado in validacoes.items():
    print(f"{descricao}: {resultado}")

# 7. Resultado consolidado
print("\nRESULTADO FINAL")

if all(validacoes.values()):
    print("Exportação validada com sucesso.")
else:
    print(
        "Há divergências na exportação. "
        "Verifique os itens marcados como False."
    )

CP5.1 — EXPORTAÇÃO DA BASE TRATADA
Arquivo: varejo_limpo.csv
Arquivo existe: True
Tamanho do arquivo (bytes): 44696814
Caminho do arquivo: /content/varejo_limpo.csv

DIMENSÕES
Base original: (830000, 14)
Base tratada: (830000, 10)
CSV exportado: (830000, 10)

VALIDAÇÕES
Arquivo não vazio: True
Registros preservados: True
Dimensões do CSV correspondem: True
Nomes e ordem das colunas correspondem: True
Sem colunas extras de índice: True
Conteúdo e ordem das linhas correspondem: True

RESULTADO FINAL
Exportação validada com sucesso.


## CP5.2 — Conclusões e comunicação dos resultados

### Principais conclusões

**1. Qualidade e tratamento dos dados**

A base original continha **830.000 registros e 14 colunas**. Durante a limpeza, foram removidas quatro colunas completamente vazias, reduzindo a estrutura para **10 colunas**, sem excluir registros.

Também foram padronizadas **3.650 ocorrências de `#N/D` em `PR_CAT`** e outras **3.650 em `PR_NOME`**, correspondentes aos registros do produto de código 107.

As **96.553 linhas completamente repetidas**, identificadas no diagnóstico, foram preservadas porque não havia evidência suficiente para comprovar que representavam erros.

Essa decisão priorizou a preservação das informações e a rastreabilidade das transformações.

**2. Distribuição das categorias por gênero e segmento**

A categoria `ALIMENTOS` apresentou a maior quantidade de registros da base, com **434.767 ocorrências**.

Na análise por gênero, sua participação foi semelhante entre os grupos: **52,38% em F** e **52,39% em M**.

O mesmo padrão foi observado entre os segmentos: **52,10% em A**, **52,40% em B** e **52,43% em C**.

Esses resultados mostram semelhança na composição percentual dos registros analisados, sem demonstrar, isoladamente, preferências individuais ou relações causais.

**3. Clientes, compras e segmentos**

A base contém **1.000 clientes distintos e 18.471 compras distintas**.

Na análise por gênero, foram identificados **519 clientes e 9.615 compras no grupo F**, comparados a **481 clientes e 8.856 compras no grupo M**.

Na comparação por segmento, o código `B` apresentou **11.843 compras distintas**, seguido por `C`, com **5.136**, e `A`, com **1.492**.

Essas quantidades representam operações e clientes identificados na base, não valores gastos nem quantidades físicas de produtos.

Os códigos dos segmentos foram mantidos sem atribuição de características comerciais não documentadas.

**4. Diversidade de produtos por compra**

A análise das **18.471 compras** identificou uma média de **39,71 códigos de produtos distintos por compra**, com mínimo de **1** e máximo de **81**.

Essa medida representa a diversidade de tipos de produtos associados às compras, e não a quantidade física de unidades vendidas.

Trata-se de uma variável quantitativa derivada dos identificadores disponíveis, cuja adequação ao critério institucional de estatísticas básicas permanece sujeita à avaliação.

**5. Frequência dos produtos e diferenças entre indicadores**

A investigação dos produtos identificou **229 códigos `PR_ID` distintos**.

O produto com mais registros foi `PR_ID 93 — AGUA SANITARIA`, com **3.773 ocorrências**.

Por compras distintas, o líder foi `PR_ID 51 — PAPINHA INFANTIL`, presente em **3.322 compras**.

Por clientes distintos, destacou-se `PR_ID 155 — PATE`, associado a **975 clientes**.

Esses resultados demonstram que os rankings mudam conforme a unidade de análise utilizada. Assim, frequência de registros, presença em compras e abrangência entre clientes são medidas diferentes.

**6. Evolução temporal das compras**

A análise temporal identificou **18.471 compras distintas**, registradas entre **4 de janeiro de 2019 e 8 de dezembro de 2022**.

Os totais anuais foram:

- **2019:** 4.483 compras;
- **2020:** 4.794 compras;
- **2021:** 5.505 compras;
- **2022:** 3.689 compras.

Foi observado crescimento entre 2019 e 2021, seguido de redução no total registrado em 2022.

A partir de setembro de 2022, ocorreu uma alteração acentuada na distribuição mensal, com **35 compras em setembro, 59 em outubro e 155 em novembro**.

Essa mudança precisa ser investigada antes de ser atribuída a fatores comerciais ou comportamentais, especialmente diante de possíveis diferenças na cobertura temporal dos dados.

### Recomendação

Recomenda-se priorizar a investigação dos **96.553 registros completamente repetidos** e dos **3.650 registros associados ao produto de código 107**, cuja identificação nominal e categórica permanece não informada.

Para isso, seria importante consultar uma fonte complementar, como um cadastro oficial de produtos ou informações adicionais capazes de distinguir ocorrências dentro de uma mesma compra.

Também se recomenda verificar a cobertura dos dados no final de 2022, antes de interpretar a redução registrada como uma tendência do negócio.

Essas verificações poderiam melhorar a confiabilidade das análises sem exigir a exclusão de dados cuja inconsistência ainda não foi comprovada.

### Limitações da análise

A base não possui campos de **quantidade física vendida, preço, valor da venda, custo ou faturamento**.

Por esse motivo, não é possível calcular diretamente unidades comercializadas, receita, ticket médio, lucro ou margem financeira.

Além disso, os registros repetidos não puderam ser classificados definitivamente como erros, e os códigos de segmento não receberam interpretações comerciais sem documentação.

As análises apresentadas são descritivas e não demonstram relações causais entre gênero, segmento, produto e comportamento de compra.

Na dimensão temporal, a cobertura do período também deve ser considerada antes de estabelecer tendências de longo prazo.

# Apêndice — README.md (CP5.3, cópia de referência)

_O conteúdo a seguir reproduz o README do projeto para consulta. O arquivo `README.md` deve permanecer como documento independente no repositório._

## Mini-Projeto — Análise de Dados de Varejo

### Identificação

**Autor:** Otávio Diniz  
**Curso:** SC TEC — Análise de Dados com Python  
**Turma:** T8  
**Módulo:** 1 — Semana 7  
**Notebook:** `Miniprojeto_Otavio_Diniz_T8.ipynb`

---

### Objetivo

O objetivo deste mini-projeto é investigar a estrutura e a qualidade de uma base de dados de varejo, aplicar procedimentos justificados de tratamento e utilizar técnicas de análise de dados com Python e a biblioteca Pandas para interpretar os resultados obtidos.

O projeto está organizado em seis Sprints, conforme o enunciado institucional:

1. **Sprint 1 — Leitura e diagnóstico:** importação e investigação da qualidade dos dados.
2. **Sprint 2 — Limpeza e padronização:** tratamento dos problemas identificados e justificativa das decisões.
3. **Sprint 3 — Funções e organização:** estruturação do processamento em funções reutilizáveis.
4. **Sprint 4 — Análise dos dados:** filtros, agrupamentos, estatísticas e investigações complementares.
5. **Sprint 5 — Exportação e comunicação:** geração da base tratada, validação da exportação e apresentação das conclusões.
6. **Sprint 6 — Revisão e entrega:** reexecução integral, conferência dos arquivos, versionamento e submissão institucional.

As cinco primeiras Sprints compõem o desenvolvimento técnico e analítico. A sexta corresponde à revisão final e à entrega.

O projeto adota como princípio metodológico compreender o significado, a estrutura e a granularidade dos dados antes de realizar alterações, evitando excluir registros ou atribuir interpretações sem evidências suficientes.

Ao final do processamento, é gerado e validado o arquivo `varejo_limpo.csv`.

---

### Fonte dos dados

**Dataset:** Base Varejo  
**Origem:** Kaggle  
**Responsável pela publicação informado no material:** João Pedro Paiva Cardoso  
**Versão informada:** 1 — 03/04/2023  
**Arquivo utilizado:** `Base Varejo.csv`

**Fonte:**

https://www.kaggle.com/datasets/namespaiva/base-varejo/data

Os dados utilizados neste projeto correspondem à base obtida para a realização do mini-projeto avaliativo.

As informações de autoria e versão acima reproduzem os metadados registrados no material do projeto. As condições de licença e redistribuição devem ser confirmadas na fonte antes da publicação pública de uma cópia integral da base.

---

### Estrutura dos dados

A base original possui **830.000 registros e 14 colunas**.

As dez colunas que contêm informações são:

| Coluna | Descrição |
|---|---|
| `DATA` | Data associada à compra |
| `CO_ID` | Identificador da compra |
| `CL_ID` | Identificador do cliente |
| `CL_GENERO` | Código de gênero registrado para o cliente |
| `CL_EC` | Código relacionado ao cliente, sem significado específico confirmado na documentação utilizada |
| `CL_FHL` | Outro código relacionado ao cliente, sem significado específico confirmado na documentação utilizada |
| `CL_SEG` | Código de segmento do cliente, com valores A, B e C |
| `PR_ID` | Identificador do produto |
| `PR_CAT` | Categoria do produto |
| `PR_NOME` | Nome do produto |

O significado comercial dos códigos `A`, `B` e `C`, assim como as definições específicas de `CL_EC` e `CL_FHL`, não foi estabelecido a partir dos dados disponíveis.

A base também continha quatro colunas completamente vazias:

- `Unnamed: 10`
- `Unnamed: 11`
- `Unnamed: 12`
- `Unnamed: 13`

Cada uma apresentava **830.000 valores ausentes**.

Essas quatro colunas foram removidas durante o tratamento.

**Estrutura final da base tratada: 830.000 registros e 10 colunas.**

---

### Como executar o projeto

O projeto foi desenvolvido para execução no **Google Colab**, utilizando Python e Pandas.

#### Pré-requisitos

- Acesso ao Google Colab.
- Arquivo `Miniprojeto_Otavio_Diniz_T8.ipynb`.
- Arquivo original `Base Varejo.csv`, obtido na fonte indicada.
- Biblioteca Pandas, disponível no ambiente utilizado.

#### Procedimento de execução

1. Abrir `Miniprojeto_Otavio_Diniz_T8.ipynb` no Google Colab.
2. Obter o arquivo `Base Varejo.csv` na fonte indicada.
3. Executar a primeira célula de código responsável pelo upload da base.
4. Quando solicitado, selecionar `Base Varejo.csv` no computador.
5. Executar as células do notebook na ordem apresentada, desde a **Sprint 1 até a Sprint 5**.
6. Acompanhar os resultados dos diagnósticos, tratamentos, agrupamentos, cálculos e validações.
7. Na Sprint 5, executar a célula CP5.1, responsável por gerar `varejo_limpo.csv`.
8. Conferir as verificações apresentadas após a exportação.
9. Localizar o arquivo gerado na área de arquivos da sessão do Google Colab e salvá-lo conforme as exigências da entrega.

O arquivo original é carregado com `pd.read_csv()`, utilizando o separador `;`.

A exportação da versão tratada utiliza:

```python
df_funcao.to_csv(
    "varejo_limpo.csv",
    index=False,
    encoding="utf-8"
)
```

O argumento `index=False` impede que o índice do DataFrame seja gravado como coluna adicional.

#### Resultado registrado na validação

Na execução documentada do CP5.1, foram obtidos:

| Verificação | Resultado |
|---|---|
| Base original | 830.000 × 14 |
| Base tratada | 830.000 × 10 |
| CSV exportado | 830.000 × 10 |
| Arquivo encontrado na sessão | True |
| Arquivo não vazio | True |
| Registros preservados | True |
| Dimensões correspondem | True |
| Nomes e ordem das colunas correspondem | True |
| Ausência de colunas extras de índice | True |
| Conteúdo e ordem das linhas correspondem | True |

**Tamanho registrado do CSV:** 44.696.814 bytes.

A execução apresentou a mensagem:

**Exportação validada com sucesso.**

Essas verificações comprovam o resultado observado na sessão executada do Colab. A existência do arquivo no ambiente de execução não substitui a conferência de sua presença no repositório de entrega.

---

### Tratamento e qualidade dos dados

O tratamento foi realizado após a investigação dos problemas identificados na base original.

#### 1. Valores ausentes

Foram encontradas quatro colunas completamente vazias, de `Unnamed: 10` a `Unnamed: 13`.

Como nenhuma dessas colunas continha valores preenchidos, sua remoção não eliminou informações registradas.

A estrutura passou de 14 para 10 colunas, mantendo os **830.000 registros**.

#### 2. Campos textuais

Foram investigadas as colunas:

`DATA`, `CL_GENERO`, `CL_SEG`, `PR_CAT` e `PR_NOME`.

Nas verificações realizadas, não foram encontrados textos vazios, valores compostos apenas por espaços ou espaços indevidos no início ou no final dos valores analisados.

#### 3. Marcadores `#N/D`

Foram identificadas:

- **3.650 ocorrências de `#N/D` em `PR_CAT`**;
- **3.650 ocorrências de `#N/D` em `PR_NOME`**.

Esses marcadores aparecem simultaneamente nas mesmas **3.650 linhas**, associadas ao produto identificado por `PR_ID = 107`.

Como não havia informação suficiente para recuperar o nome e a categoria desse produto, os valores foram apenas padronizados:

| Coluna | Valor original | Valor tratado |
|---|---|---|
| `PR_CAT` | `#N/D` | `NÃO INFORMADA` |
| `PR_NOME` | `#N/D` | `NÃO INFORMADO` |

Não foi atribuído um nome ou uma categoria por inferência.

#### 4. Registros repetidos

O diagnóstico identificou dois indicadores distintos:

- **96.553 ocorrências excedentes de linhas completamente repetidas**, considerando todas as colunas.
- **184.330 linhas envolvidas em combinações repetidas de `PR_ID + PR_NOME + CO_ID + CL_ID`**, incluindo as primeiras ocorrências e suas repetições.

Esses indicadores possuem critérios de contagem diferentes e não devem ser considerados equivalentes.

As linhas repetidas **não foram eliminadas**, pois a base não possui uma coluna de quantidade física vendida nem um identificador individual do item dentro da compra.

Assim, duas linhas aparentemente iguais podem representar uma duplicação indevida ou duas ocorrências legítimas do mesmo produto em uma compra.

A exclusão sem confirmação poderia provocar perda de informação válida.

#### 5. Consistência dos identificadores

Foram realizadas verificações utilizando `groupby()` e `nunique()`.

As relações investigadas não apresentaram divergências:

| Verificação | Divergências encontradas |
|---|---:|
| Compra associada a mais de um cliente | 0 |
| Compra associada a mais de uma data | 0 |
| Cliente associado a mais de um gênero | 0 |
| Cliente associado a mais de um segmento | 0 |
| Produto associado a mais de um nome | 0 |
| Produto associado a mais de uma categoria | 0 |
| Cliente com valores divergentes em `CL_EC` | 0 |
| Cliente com valores divergentes em `CL_FHL` | 0 |

As decisões de limpeza foram fundamentadas nesses diagnósticos.

---

### Organização do processamento

#### Sprint 1 — Leitura e diagnóstico

O arquivo original é carregado para o DataFrame `df_bruto`, utilizando `pd.read_csv()`.

O notebook apresenta as primeiras linhas, as dimensões, os nomes das colunas, os tipos de dados e as verificações iniciais de qualidade.

#### Sprint 2 — Limpeza e padronização

A limpeza é aplicada sobre uma cópia dos dados originais.

O procedimento remove as quatro colunas completamente vazias e padroniza os marcadores `#N/D` dos campos do produto 107.

Os registros são preservados quando não existe justificativa suficiente para exclusão.

#### Sprint 3 — Funções e organização

O tratamento é organizado em uma função reutilizável, `tratar_dados()`, que recebe os dados, aplica as transformações definidas e retorna a versão tratada.

O notebook também utiliza uma função de resumo para apresentar indicadores da base.

Essa organização facilita a reutilização e torna a sequência de processamento mais clara.

#### Sprint 4 — Análise dos dados

A Sprint 4 contém oito checkpoints:

| Checkpoint | Investigação |
|---|---|
| CP4.1 | Filtro por categoria |
| CP4.2 | Agrupamentos por categoria e segmento |
| CP4.3 | Estatísticas de diversidade de produtos por compra |
| CP4.4 | Perfil dos clientes por gênero |
| CP4.5 | Categorias de produtos por gênero |
| CP4.6 | Categorias de produtos por segmento |
| CP4.7 | Frequência dos produtos por registros, compras e clientes |
| CP4.8 | Evolução temporal das compras distintas |

As análises diferenciam registros, compras e clientes distintos, respeitando a unidade de cada indicador.

#### Sprint 5 — Exportação e comunicação

A Sprint 5 compreende três checkpoints:

- **CP5.1:** exportação e validação da base tratada.
- **CP5.2:** apresentação de seis conclusões sustentadas por resultados numéricos, acompanhadas de recomendação e limitações.
- **CP5.3:** documentação do projeto no README.

#### Sprint 6 — Revisão e entrega

Esta etapa corresponde à reexecução completa do projeto, à conferência dos arquivos, à organização do repositório, ao registro dos commits e à submissão do link no AVA.

A conclusão institucional dessa etapa depende da realização e da comprovação dessas ações, não apenas da documentação apresentada neste README.

---

### Leitura, transformação e gravação dos dados

A leitura da base original ocorre na Sprint 1, utilizando `pd.read_csv()`. A transformação é investigada e justificada na Sprint 2 e organizada na função `tratar_dados()` na Sprint 3. Na Sprint 5, a base tratada é gravada como `varejo_limpo.csv`, utilizando `to_csv(index=False)`, e relida para validação.

A remoção das quatro colunas completamente vazias reduziu a estrutura de 14 para 10 colunas sem excluir registros. A padronização dos marcadores `#N/D` também tornou explícita a ausência de informações do produto 107, preservando a rastreabilidade dos dados.

O fluxo principal pode ser representado por:

**Base Varejo.csv → leitura → diagnóstico → investigação → tratamento → funções → análises → exportação → validação do CSV → comunicação dos resultados**

---

### Principais conclusões

#### 1. Qualidade e tratamento dos dados

A base original continha **830.000 registros e 14 colunas**.

Durante a limpeza, foram removidas quatro colunas completamente vazias, reduzindo a estrutura para **10 colunas**, sem excluir registros.

Também foram padronizadas **3.650 ocorrências de `#N/D` em `PR_CAT`** e outras **3.650 em `PR_NOME`**, correspondentes aos registros do produto de código 107.

As **96.553 ocorrências excedentes de linhas completamente repetidas**, identificadas no diagnóstico, foram preservadas porque não havia evidência suficiente para comprovar que representavam erros.

Essa decisão priorizou a preservação das informações e a rastreabilidade das transformações.

#### 2. Distribuição das categorias por gênero e segmento

A categoria `ALIMENTOS` apresentou a maior quantidade de registros da base, com **434.767 ocorrências**.

Na análise por gênero, sua participação foi semelhante entre os grupos: **52,38% em F** e **52,39% em M**.

O mesmo padrão foi observado entre os segmentos: **52,10% em A**, **52,40% em B** e **52,43% em C**.

Esses resultados mostram semelhança na composição percentual dos registros analisados, sem demonstrar, isoladamente, preferências individuais ou relações causais.

#### 3. Clientes, compras e segmentos

A base contém **1.000 clientes distintos e 18.471 compras distintas**.

Na análise por gênero, foram identificados **519 clientes e 9.615 compras no grupo F**, comparados a **481 clientes e 8.856 compras no grupo M**.

Na comparação por segmento, o código `B` apresentou **11.843 compras distintas**, seguido por `C`, com **5.136**, e `A`, com **1.492**.

Essas quantidades representam operações e clientes identificados na base, não valores gastos nem quantidades físicas de produtos.

Os códigos dos segmentos foram mantidos sem atribuição de características comerciais não documentadas.

#### 4. Diversidade de produtos por compra

A análise das **18.471 compras** identificou uma média de **39,71 códigos de produtos distintos por compra**, com mínimo de **1** e máximo de **81**.

Essa medida representa a diversidade de tipos de produtos associados às compras, e não a quantidade física de unidades vendidas.

Trata-se de uma variável quantitativa derivada dos identificadores disponíveis, cuja adequação ao critério institucional de estatísticas básicas permanece sujeita à avaliação.

#### 5. Frequência dos produtos e diferenças entre indicadores

A investigação dos produtos identificou **229 códigos `PR_ID` distintos**.

O produto com mais registros foi `PR_ID 93 — AGUA SANITARIA`, com **3.773 ocorrências**.

Por compras distintas, o líder foi `PR_ID 51 — PAPINHA INFANTIL`, presente em **3.322 compras**.

Por clientes distintos, destacou-se `PR_ID 155 — PATE`, associado a **975 clientes**.

Esses resultados demonstram que os rankings mudam conforme a unidade de análise utilizada. Assim, frequência de registros, presença em compras e abrangência entre clientes são medidas diferentes.

#### 6. Evolução temporal das compras

A análise temporal identificou **18.471 compras distintas**, registradas entre **4 de janeiro de 2019 e 8 de dezembro de 2022**.

Os totais anuais foram:

- **2019:** 4.483 compras;
- **2020:** 4.794 compras;
- **2021:** 5.505 compras;
- **2022:** 3.689 compras.

Foi observado crescimento entre 2019 e 2021, seguido de redução no total registrado em 2022.

A partir de setembro de 2022, ocorreu uma alteração acentuada na distribuição mensal, com **35 compras em setembro, 59 em outubro e 155 em novembro**.

Essa mudança precisa ser investigada antes de ser atribuída a fatores comerciais ou comportamentais, especialmente diante de possíveis diferenças na cobertura temporal dos dados.

---

### Recomendação

Recomenda-se priorizar a investigação das **96.553 ocorrências excedentes de linhas completamente repetidas** e dos **3.650 registros associados ao produto de código 107**, cuja identificação nominal e categórica permanece não informada.

Para isso, seria importante consultar uma fonte complementar, como um cadastro oficial de produtos ou informações adicionais capazes de distinguir ocorrências dentro de uma mesma compra.

Também se recomenda verificar a cobertura dos dados no final de 2022, antes de interpretar a redução registrada como uma tendência do negócio.

Essas verificações poderiam melhorar a confiabilidade das análises sem exigir a exclusão de dados cuja inconsistência ainda não foi comprovada.

---

### Limitações da análise

A base não possui campos de **quantidade física vendida, preço, valor da venda, custo ou faturamento**.

Por esse motivo, não é possível calcular diretamente unidades comercializadas, receita, ticket médio, lucro ou margem financeira.

Além disso, os registros repetidos não puderam ser classificados definitivamente como erros, e os códigos de segmento não receberam interpretações comerciais sem documentação.

As análises apresentadas são descritivas e não demonstram relações causais entre gênero, segmento, produto e comportamento de compra.

Na dimensão temporal, a cobertura do período também deve ser considerada antes de estabelecer tendências de longo prazo.

Existe ainda uma ressalva metodológica no CP4.3: a medida de diversidade foi calculada a partir de identificadores de produtos e compras. Embora seja quantitativa e interpretável, não corresponde a uma coluna numérica original da base, e sua aderência à exigência específica da avaliação não está comprovada.

---

### Arquivos do projeto

Os principais arquivos previstos para a entrega são:

| Arquivo | Finalidade |
|---|---|
| `Miniprojeto_Otavio_Diniz_T8.ipynb` | Notebook com leitura, diagnóstico, tratamento, funções, análises e exportação |
| `varejo_limpo.csv` | Base tratada gerada pelo notebook |
| `README.md` | Documentação, metodologia, instruções e conclusões |

O arquivo original `Base Varejo.csv` é o dado de entrada e pode ser obtido na fonte indicada.

A publicação pública dos arquivos deverá respeitar as condições de utilização e redistribuição do dataset.

---

### Referências

**Base Varejo — Kaggle**

https://www.kaggle.com/datasets/namespaiva/base-varejo/data

**Pandas — Documentação oficial**

https://pandas.pydata.org/docs/

---

### Nota metodológica final

O projeto prioriza a análise fundamentada nos dados efetivamente disponíveis.

As decisões de tratamento foram registradas, os indicadores foram interpretados de acordo com suas unidades e as limitações da base foram preservadas na comunicação dos resultados.

O objetivo é apresentar um processo de análise exploratória compreensível, rastreável e reproduzível, sem atribuir aos dados informações ou conclusões que não possam ser sustentadas pelos resultados observados.